
<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.Blog -->

	<h2>
<!-- start oip-atom-subtitle.txt -->
<a data-id="4f926db3-f622-402e-882d-16ab58f085a7_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">Weconomy Start Kickoff Video, 22 January 2013</a>
<!-- end oip-atom-subtitle.txt -->



		<br>
		<small>
<!-- start oip-atom-subtitle.txt -->
<span class="small-before-after"/>"</span>
<a data-id="4f926db3-f622-402e-882d-16ab58f085a7_SubTitle"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit"></a>
<span class="small-before-after"/>"</span>
<!-- end oip-atom-subtitle.txt -->
</small>
	</h2>
</div>
<div class="multicolumnElement" style="padding-left:15px;padding-right:15px;">
    <p>
        <img src="../AaltoGlobalImpact.OIP/MediaContent/748523b3-e6e2-4fa7-9b33-b44d2a754833_320x240_crop.jpg" />
    </p>
	<p>
		Video form the Weconomy Kickoff on 22 January 2013:<br>http://www.youtube.com/watch?v=pl23Q_EbF1s&amp;feature=share&amp;list=PLBqI16BTiSbS78DV1qrLH5brMKchglflu<br><br>The programme was coordinated by World Vision Finland together with Finpro, Aalto University, World Vision India and World Vision Sri Lanka.<br>For more inofrmation of the event please visit this link: <a target="_blank" title="" href="http://www.aaltoglobalimpact.org/events/invitation-weconomy-start-kickoff-22-january-2013">Weconomy Start Kickoff, 22 January 2013</a><br>
	</p>
</div>
<div>
	<div id="flowcontainer" class="thumbnails">
		
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImageGroupCollection -->



	</div>
	<br>
	<iframe width="560" height="315" src="http://www.youtube.com/embed/pl23Q_EbF1s?list=PLBqI16BTiSbS78DV1qrLH5brMKchglflu" frameborder="0" allowfullscreen></iframe>

<iframe width="560" height="315" src="http://www.youtube.com/embed/uPcLoTtRp0k" frameborder="0" allowfullscreen></iframe>
<script>
    $(function(){
      var $container = $('#flowcontainer');
      $container.isotope({
        itemSelector: '.oipimagecollection'
      });
    });
</script>
</div>
<div class="reading-pane-footer">
    <div class="meta">
        <!--
        using same <dl></dl> as in tiles
        -->
        <dl class="dl-horizontal date"><dt>on</dt><dd>3/19/2013 12:57:31 PM</dd></dl>
        <dl class="dl-horizontal author"><dt>by</dt><dd>Aalto Global Impact</dd></dl>
    </div>
    <div class="controls">
        <ul class="inline">
            <li>
                <form>
                    <i class="icon-bookmark"></i>
                    <input class="text" name="share_url" value="http://www.aaltoglobalimpact.org/www-public/oip-layout-landing.phtml?type=news&id=4f926db3-f622-402e-882d-16ab58f085a7">
                </form>
            </li>
        </ul>
    </div>
</div>


<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.Blog -->


