
<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.Blog -->

	<h2>
<!-- start oip-atom-subtitle.txt -->
<a data-id="6eb6fdd7-c191-4102-af37-88666c2aaa33_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">Aalto Global Impact Open Doors @ Design Factory on March 20</a>
<!-- end oip-atom-subtitle.txt -->



		<br>
		<small>
<!-- start oip-atom-subtitle.txt -->
<span class="small-before-after"/>"</span>
<a data-id="6eb6fdd7-c191-4102-af37-88666c2aaa33_SubTitle"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit"></a>
<span class="small-before-after"/>"</span>
<!-- end oip-atom-subtitle.txt -->
</small>
	</h2>
</div>
<div class="multicolumnElement" style="padding-left:15px;padding-right:15px;">
    <p>
        <img src="../AaltoGlobalImpact.OIP/MediaContent/f4172153-9e91-4c21-9eaa-fc52fbe311b1_320x240_crop.jpg" />
    </p>
	<p>
		We would love to spend the International Day of Happiness with you in Aalto Global Impact Open Doors @ Design Factory on March 20, 15:00-18:00. <br><br>We are opening a newly renovated space for you to use at your leisure and call home whilst visiting the Design Factory.<br><br>Drinks and snacks will be available and we encourage you to visit and interact with the Aalto Global Impact Team as your thoughts on the space plus our community development and interactions are much appreciated and valued. See the invitation here.<br><br>Please register for the event here: http://www.webropolsurveys.com/S/C16E4482F066422C.par <br>
	</p>
</div>
<div>
	<div id="flowcontainer" class="thumbnails">
		
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImageGroupCollection -->



	</div>
	<br>
	
<script>
    $(function(){
      var $container = $('#flowcontainer');
      $container.isotope({
        itemSelector: '.oipimagecollection'
      });
    });
</script>
</div>
<div class="reading-pane-footer">
    <div class="meta">
        <!--
        using same <dl></dl> as in tiles
        -->
        <dl class="dl-horizontal date"><dt>on</dt><dd>3/20/2013 12:00:00 AM</dd></dl>
        <dl class="dl-horizontal author"><dt>by</dt><dd>Aalto Global Impact</dd></dl>
    </div>
    <div class="controls">
        <ul class="inline">
            <li>
                <form>
                    <i class="icon-bookmark"></i>
                    <input class="text" name="share_url" value="http://www.aaltoglobalimpact.org/www-public/oip-layout-landing.phtml?type=news&id=6eb6fdd7-c191-4102-af37-88666c2aaa33">
                </form>
            </li>
        </ul>
    </div>
</div>


<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.Blog -->


