
<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.Activity -->

<h2><a data-id="6d4ae4e2-7c29-4df4-b59d-4d9dcd6ffcd1_ActivityName" title="Edit Activity Name" class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">South Africa: World Design Capital 2012-2014, Helsinki meets Cape Town</a>

</h2>

<!-- THEBALL-CONTEXT-OBJECT-BEGIN:Introduction -->

<!-- oip-module-introduction.txt -->
<h3>

<!-- start oip-atom-subtitle.txt -->
<a data-id="71877d78-7c0d-4b09-87a3-2142e0235d65_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit"></a>
<!-- end oip-atom-subtitle.txt -->



</h3>
<p>
<a data-id="71877d78-7c0d-4b09-87a3-2142e0235d65_Body"  class="noteditable open-IncontextEditDialog_Text_Long in-context-edit"></a>

</p>
<!-- end oip-module-introduction.txt -->


<!-- THEBALL-CONTEXT-END:Introduction -->

</div>
<div class="multicolumnElement" style="padding-left:15px;padding-right:15px;">
    <p>
        <img src="../AaltoGlobalImpact.OIP/MediaContent/be9e0c5d-e129-4ebd-a1f4-f11344d3dc6e_320x240_crop.jpg" />
    </p>
    <p>The succeeding World Design Capital years of Helsinki in 2012 and Cape Town in 2014 provide a unique opportunity for furthering partnerships between Finland and South Africa. This project aims at creating space for new longer-term collaboration and business opportunities between the two countries.</p>
</div>
<div>
	<div id="flowcontainer" class="thumbnails">
		
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImageGroupCollection -->



	</div>
	<br>
	
<script>
	$(function(){
		var $container = $('#flowcontainer');
		$container.isotope({
		itemSelector: '.oipimagecollection'
		});
	});
</script>
</div>
<div class="reading-pane-footer">
    <div class="meta">
        <!--
        using same <dl></dl> as in tiles
        -->
        <dl class="dl-horizontal date"><dt>on</dt><dd>1/1/0001 12:00:00 AM</dd></dl>
        <dl class="dl-horizontal author"><dt>by</dt><dd></dd></dl>
    </div>
    <div class="controls">
        <ul class="inline">
            <li>
                <form>
                    <i class="icon-bookmark"></i>
                    <input class="text" name="share_url" value="http://www.aaltoglobalimpact.org/www-public/oip-layout-landing.phtml?type=activity&id=6d4ae4e2-7c29-4df4-b59d-4d9dcd6ffcd1">
                </form>
            </li>
        </ul>
    </div>
</div>


<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.Activity -->


