
<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.Activity -->

<h2><a data-id="338fdac8-83a6-476b-a7e7-a56c0860f884_ActivityName" title="Edit Activity Name" class="noteditable open-IncontextEditDialog_Text_Short in-context-edit"></a>

</h2>

<!-- THEBALL-CONTEXT-OBJECT-BEGIN:Introduction -->

<!-- oip-module-introduction.txt -->
<h3>

<!-- start oip-atom-subtitle.txt -->
<a data-id="76297c74-58ff-4bd0-9967-8a5cec4e0e67_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit"></a>
<!-- end oip-atom-subtitle.txt -->



</h3>
<p>
<a data-id="76297c74-58ff-4bd0-9967-8a5cec4e0e67_Body"  class="noteditable open-IncontextEditDialog_Text_Long in-context-edit"></a>

</p>
<!-- end oip-module-introduction.txt -->


<!-- THEBALL-CONTEXT-END:Introduction -->

</div>
<div class="multicolumnElement" style="padding-left:15px;padding-right:15px;">
    <p>
        <img src="AaltoGlobalImpact.OIP/MediaContent/2a72431a-ede2-4077-99d8-01a5b80e03f8_320x240_crop.jpg" />
    </p>
    <p></p>
</div>
<div>
	<div id="flowcontainer" class="thumbnails">
		
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImageGroupCollection -->



<div class="oipimagecollection">
    <a data-toggle="modal" href="#ImagesCollection51cf81aa-4398-4264-8207-6663327f3e35" rel="tooltip" title="click this image to open this image large and some other images if present">
        <img src="../AaltoGlobalImpact.OIP/MediaContent/b04c3340-6a23-43f1-89e1-e97fe31eda0f_320x240_crop.jpg" class="thumbnail" alt="News Letter December 2012"/>
        <br>
        News Letter December 2012
    </a>
</div>

<div id="ImagesCollection51cf81aa-4398-4264-8207-6663327f3e35" class="modal hide fade">
	<div class="modal-header">
		<button class="close" data-dismiss="modal">&times;</button>
		<h2 class="title">News Letter December 2012</h2>
		<p>Current Activities </p>
	</div>
	<div class="modal-body">
		<div id="#myCarousel51cf81aa-4398-4264-8207-6663327f3e35" class="carousel">
			<!-- Carousel items -->
			<div class="columns">
				<div id="myCarousel51cf81aa-4398-4264-8207-6663327f3e35" class="carousel slide image-carousel">
					<div class="carousel-inner">
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImagesCollection -->


						<div class="item">
							<img src="../AaltoGlobalImpact.OIP/MediaContent/ebf43041-e1d4-458b-b838-9f1a3f5736ed_1280x720_whole.jpg" alt="Organizing the market place">
							<div class="carousel-caption">
								<h4>ACCESS: Design Needs Your Voice!</h4>
								<p>Organizing the market place</p>
							</div>
						</div>

<!-- THEBALL-CONTEXT-END:* -->

						<div class="item">
							<img src="../AaltoGlobalImpact.OIP/MediaContent/816d9d2b-0e08-4a0f-9d2a-2face2ad800d_1280x720_whole.jpg" alt="Laura Ansala from Aalto University wins first Master’s Award in Development Studies">
							<div class="carousel-caption">
								<h4>Laura Ansala</h4>
								<p>Laura Ansala from Aalto University wins first Master’s Award in Development Studies</p>
							</div>
						</div>

<!-- THEBALL-CONTEXT-END:* -->

					</div>
					<a class="left carousel-control" href="#myCarousel51cf81aa-4398-4264-8207-6663327f3e35" data-slide="prev">‹</a>
					<a class="right carousel-control" href="#myCarousel51cf81aa-4398-4264-8207-6663327f3e35" data-slide="next">›</a>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end oip-module-modal-images.txt -->



<!-- THEBALL-CONTEXT-END:ImageGroupCollection -->


<div class="oipimagecollection">
    <a data-toggle="modal" href="#ImagesCollection6a69f84a-4a0e-461d-9017-4720f0a54d4b" rel="tooltip" title="click this image to open this image large and some other images if present">
        <img src="../AaltoGlobalImpact.OIP/MediaContent/a25982c0-7efa-475b-aba9-a775b62491b0_320x240_crop.jpg" class="thumbnail" alt="Talkoot"/>
        <br>
        Talkoot
    </a>
</div>

<div id="ImagesCollection6a69f84a-4a0e-461d-9017-4720f0a54d4b" class="modal hide fade">
	<div class="modal-header">
		<button class="close" data-dismiss="modal">&times;</button>
		<h2 class="title">Talkoot</h2>
		<p>Cross-community Design workshop, Cape Town, South Africa</p>
	</div>
	<div class="modal-body">
		<div id="#myCarousel6a69f84a-4a0e-461d-9017-4720f0a54d4b" class="carousel">
			<!-- Carousel items -->
			<div class="columns">
				<div id="myCarousel6a69f84a-4a0e-461d-9017-4720f0a54d4b" class="carousel slide image-carousel">
					<div class="carousel-inner">
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImagesCollection -->


						<div class="item">
							<img src="../AaltoGlobalImpact.OIP/MediaContent/d52c7749-0027-4b0b-a8ea-9cdf90ca60df_1280x720_whole.jpg" alt="1">
							<div class="carousel-caption">
								<h4>1</h4>
								<p>1</p>
							</div>
						</div>

<!-- THEBALL-CONTEXT-END:* -->

					</div>
					<a class="left carousel-control" href="#myCarousel6a69f84a-4a0e-461d-9017-4720f0a54d4b" data-slide="prev">‹</a>
					<a class="right carousel-control" href="#myCarousel6a69f84a-4a0e-461d-9017-4720f0a54d4b" data-slide="next">›</a>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end oip-module-modal-images.txt -->



<!-- THEBALL-CONTEXT-END:ImageGroupCollection -->


<div class="oipimagecollection">
    <a data-toggle="modal" href="#ImagesCollection80b0c569-0c1a-4841-b53a-778e18a5942c" rel="tooltip" title="click this image to open this image large and some other images if present">
        <img src="../AaltoGlobalImpact.OIP/MediaContent/94c7b46a-1eb5-4975-b143-d66ee3268122_320x240_crop.jpg" class="thumbnail" alt="Test image group 2"/>
        <br>
        Test image group 2
    </a>
</div>

<div id="ImagesCollection80b0c569-0c1a-4841-b53a-778e18a5942c" class="modal hide fade">
	<div class="modal-header">
		<button class="close" data-dismiss="modal">&times;</button>
		<h2 class="title">Test image group 2</h2>
		<p>Test image group 2 description</p>
	</div>
	<div class="modal-body">
		<div id="#myCarousel80b0c569-0c1a-4841-b53a-778e18a5942c" class="carousel">
			<!-- Carousel items -->
			<div class="columns">
				<div id="myCarousel80b0c569-0c1a-4841-b53a-778e18a5942c" class="carousel slide image-carousel">
					<div class="carousel-inner">
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImagesCollection -->


						<div class="item">
							<img src="../AaltoGlobalImpact.OIP/MediaContent/94c7b46a-1eb5-4975-b143-d66ee3268122_1280x720_whole.jpg" alt="Just for demonstration">
							<div class="carousel-caption">
								<h4>Kalle's face</h4>
								<p>Just for demonstration</p>
							</div>
						</div>

<!-- THEBALL-CONTEXT-END:* -->

						<div class="item">
							<img src="../AaltoGlobalImpact.OIP/MediaContent/e7eaed4a-e1a4-4b16-a3bc-bd9ce7867ab2_1280x720_whole.jpg" alt="Another ">
							<div class="carousel-caption">
								<h4>Kalle's face 2</h4>
								<p>Another </p>
							</div>
						</div>

<!-- THEBALL-CONTEXT-END:* -->

					</div>
					<a class="left carousel-control" href="#myCarousel80b0c569-0c1a-4841-b53a-778e18a5942c" data-slide="prev">‹</a>
					<a class="right carousel-control" href="#myCarousel80b0c569-0c1a-4841-b53a-778e18a5942c" data-slide="next">›</a>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end oip-module-modal-images.txt -->



<!-- THEBALL-CONTEXT-END:ImageGroupCollection -->


<div class="oipimagecollection">
    <a data-toggle="modal" href="#ImagesCollectionbb0f5b28-ad1f-406e-9afa-779d5f42d152" rel="tooltip" title="click this image to open this image large and some other images if present">
        <img src="../AaltoGlobalImpact.OIP/MediaContent/6a73d48d-dec0-4c4d-9100-df534401c7f8_320x240_crop.jpg" class="thumbnail" alt="ACCESS"/>
        <br>
        ACCESS
    </a>
</div>

<div id="ImagesCollectionbb0f5b28-ad1f-406e-9afa-779d5f42d152" class="modal hide fade">
	<div class="modal-header">
		<button class="close" data-dismiss="modal">&times;</button>
		<h2 class="title">ACCESS</h2>
		<p>Exploring Opportunity Gaps, Cape Town, South Africa</p>
	</div>
	<div class="modal-body">
		<div id="#myCarouselbb0f5b28-ad1f-406e-9afa-779d5f42d152" class="carousel">
			<!-- Carousel items -->
			<div class="columns">
				<div id="myCarouselbb0f5b28-ad1f-406e-9afa-779d5f42d152" class="carousel slide image-carousel">
					<div class="carousel-inner">
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImagesCollection -->


						<div class="item">
							<img src="../AaltoGlobalImpact.OIP/MediaContent/6a73d48d-dec0-4c4d-9100-df534401c7f8_1280x720_whole.jpg" alt="Workshop bringing together some 80 participants from Finland and South Africa.">
							<div class="carousel-caption">
								<h4>ACCESS_CPUT_08112012</h4>
								<p>Workshop bringing together some 80 participants from Finland and South Africa.</p>
							</div>
						</div>

<!-- THEBALL-CONTEXT-END:* -->

						<div class="item">
							<img src="../AaltoGlobalImpact.OIP/MediaContent/e5592f80-4b08-4b96-ad80-3b231f943d62_1280x720_whole.jpg" alt="">
							<div class="carousel-caption">
								<h4></h4>
								<p></p>
							</div>
						</div>

<!-- THEBALL-CONTEXT-END:* -->

					</div>
					<a class="left carousel-control" href="#myCarouselbb0f5b28-ad1f-406e-9afa-779d5f42d152" data-slide="prev">‹</a>
					<a class="right carousel-control" href="#myCarouselbb0f5b28-ad1f-406e-9afa-779d5f42d152" data-slide="next">›</a>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end oip-module-modal-images.txt -->



<!-- THEBALL-CONTEXT-END:ImageGroupCollection -->


<div class="oipimagecollection">
    <a data-toggle="modal" href="#ImagesCollectionf9dcf387-a5f4-4943-af79-7a3b6e1fbe1f" rel="tooltip" title="click this image to open this image large and some other images if present">
        <img src="../AaltoGlobalImpact.OIP/MediaContent/ebeeab45-83ac-4efa-963d-9252e8d1d8d8_320x240_crop.jpg" class="thumbnail" alt="World Bank "/>
        <br>
        World Bank 
    </a>
</div>

<div id="ImagesCollectionf9dcf387-a5f4-4943-af79-7a3b6e1fbe1f" class="modal hide fade">
	<div class="modal-header">
		<button class="close" data-dismiss="modal">&times;</button>
		<h2 class="title">World Bank </h2>
		<p>Aalto - World Bank partnership: Training Program on Innovation Policy for ICT</p>
	</div>
	<div class="modal-body">
		<div id="#myCarouself9dcf387-a5f4-4943-af79-7a3b6e1fbe1f" class="carousel">
			<!-- Carousel items -->
			<div class="columns">
				<div id="myCarouself9dcf387-a5f4-4943-af79-7a3b6e1fbe1f" class="carousel slide image-carousel">
					<div class="carousel-inner">
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImagesCollection -->


						<div class="item">
							<img src="../AaltoGlobalImpact.OIP/MediaContent/ebeeab45-83ac-4efa-963d-9252e8d1d8d8_1280x720_whole.jpg" alt="Aalto - World Bank partnership: Training Program on Innovation Policy for ICT">
							<div class="carousel-caption">
								<h4>World Bank Training </h4>
								<p>Aalto - World Bank partnership: Training Program on Innovation Policy for ICT</p>
							</div>
						</div>

<!-- THEBALL-CONTEXT-END:* -->

						<div class="item">
							<img src="../AaltoGlobalImpact.OIP/MediaContent/a0b3ba2e-cf7a-412e-b81f-e6657e6c7991_1280x720_whole.jpg" alt="Aalto - World Bank partnership: Training Program on Innovation Policy for ICT">
							<div class="carousel-caption">
								<h4>World Bank Training </h4>
								<p>Aalto - World Bank partnership: Training Program on Innovation Policy for ICT</p>
							</div>
						</div>

<!-- THEBALL-CONTEXT-END:* -->

						<div class="item">
							<img src="AaltoGlobalImpact.OIP/MediaContent/e302f7b8-b530-4856-9c16-c2be01b64bc1_1280x720_whole.jpg" alt="">
							<div class="carousel-caption">
								<h4></h4>
								<p></p>
							</div>
						</div>

<!-- THEBALL-CONTEXT-END:* -->

						<div class="item">
							<img src="../AaltoGlobalImpact.OIP/MediaContent/326128ee-c660-4963-8fe8-885c196fa3d0_1280x720_whole.jpg" alt="">
							<div class="carousel-caption">
								<h4>Logo</h4>
								<p></p>
							</div>
						</div>

<!-- THEBALL-CONTEXT-END:* -->

					</div>
					<a class="left carousel-control" href="#myCarouself9dcf387-a5f4-4943-af79-7a3b6e1fbe1f" data-slide="prev">‹</a>
					<a class="right carousel-control" href="#myCarouself9dcf387-a5f4-4943-af79-7a3b6e1fbe1f" data-slide="next">›</a>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end oip-module-modal-images.txt -->



<!-- THEBALL-CONTEXT-END:ImageGroupCollection -->


	</div>
	<br>
	
<script>
	$(function(){
		var $container = $('#flowcontainer');
		$container.isotope({
		itemSelector: '.oipimagecollection'
		});
	});
</script>
</div>
<div class="reading-pane-footer">
    <div class="meta">
        <!--
        using same <dl></dl> as in tiles
        -->
        <dl class="dl-horizontal date"><dt>on</dt><dd>1/1/0001 12:00:00 AM</dd></dl>
        <dl class="dl-horizontal author"><dt>by</dt><dd></dd></dl>
    </div>
    <div class="controls">
        <ul class="inline">
            <li>
                <form>
                    <i class="icon-bookmark"></i>
                    <input class="text" name="share_url" value="http://www.aaltoglobalimpact.org/www-public/oip-layout-landing.phtml?type=activity&id=338fdac8-83a6-476b-a7e7-a56c0860f884">
                </form>
            </li>
        </ul>
    </div>
</div>


<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.Activity -->


