
<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.Blog -->

	<h2>
<!-- start oip-atom-subtitle.txt -->
<a data-id="9a739f07-2d32-451e-9143-387b5f36a37c_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">Invitation to event: Companies and NGOs - from Greenwashing to Innovations?</a>
<!-- end oip-atom-subtitle.txt -->



		<br>
		<small>
<!-- start oip-atom-subtitle.txt -->
<span class="small-before-after"/>"</span>
<a data-id="9a739f07-2d32-451e-9143-387b5f36a37c_SubTitle"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit"></a>
<span class="small-before-after"/>"</span>
<!-- end oip-atom-subtitle.txt -->
</small>
	</h2>
</div>
<div class="multicolumnElement" style="padding-left:15px;padding-right:15px;">
    <p>
        <img src="../AaltoGlobalImpact.OIP/MediaContent/0ad026f2-9de5-4e48-9acf-152704fe9339_320x240_crop.jpg" />
    </p>
	<p>
		<p>In partnership with UNICEF Finland, Aalto Global Impact hosted an event Companies and NGOs - from Greenwashing to Innovations? on the 21st of November. </p>

<p>The <a target="_blank" title="" href="http://www.aaltoglobalimpact.org/file_download/6/Invitation+letter_311012_5.pdf">program</a> included speeches and presentations by Teija Lehtonen (Aalto Global Impact), Tom Selänniemi (UNICEF Finland), Timo Lehesvirta (UPM), Kati Ihamäki (Finnair), and Prof. Mikko Jääskeläinen (Institute of Strategy, Aalto University). Miika Korppi (Aalto University) presented the findings of his recently completed Master's thesis research "Corporate collaboration strategies for the Finnish development and emergency aid organizations". (see Miika's <a target="_blank" title="" href="http://www.aaltoglobalimpact.org/file_download/7/Thesis_presentation_21_11_2012.pdf">presentation</a> or the <a target="_blank" title="" href="https://docs.google.com/viewer?a=v&amp;pid=sites&amp;srcid=ZGVmYXVsdGRvbWFpbnxhYWx0b3didHJhaW5pbmdzfGd4OjE4OWIyYTAwNzgxMzYyZQ">whole thesis</a>).</p>

<p>The discussion session in the end of the event over light snacks and beverages was an excellent opportunity for participanting guests from within Aalto University, NGOs, business and government to share their impressions and ideas with each other and for networking.</p>
<p>Thank you for joining us in this event and looking forward to seeing you in our next events!</p><font face="Calibri" size="3"><font face="Calibri" size="3"><span lang=""></span></font></font>
	</p>
</div>
<div>
	<div id="flowcontainer" class="thumbnails">
		
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImageGroupCollection -->



	</div>
	<br>
	
<script>
    $(function(){
      var $container = $('#flowcontainer');
      $container.isotope({
        itemSelector: '.oipimagecollection'
      });
    });
</script>
</div>
<div class="reading-pane-footer">
    <div class="meta">
        <!--
        using same <dl></dl> as in tiles
        -->
        <dl class="dl-horizontal date"><dt>on</dt><dd>11/2/2012 1:15:30 PM</dd></dl>
        <dl class="dl-horizontal author"><dt>by</dt><dd>Aalto Global Impact</dd></dl>
    </div>
    <div class="controls">
        <ul class="inline">
            <li>
                <form>
                    <i class="icon-bookmark"></i>
                    <input class="text" name="share_url" value="http://www.aaltoglobalimpact.org/www-public/oip-layout-landing.phtml?type=news&id=9a739f07-2d32-451e-9143-387b5f36a37c">
                </form>
            </li>
        </ul>
    </div>
</div>


<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.Blog -->


