
<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.Activity -->

<h2><a data-id="693ee0b1-278c-4de1-9dbb-7e9befb1f13f_ActivityName" title="Edit Activity Name" class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">Uganda: Water, Sanitation and Hygiene</a>

</h2>

<!-- THEBALL-CONTEXT-OBJECT-BEGIN:Introduction -->

<!-- oip-module-introduction.txt -->
<h3>

<!-- start oip-atom-subtitle.txt -->
<a data-id="7298a802-a54a-44bb-a02d-d82d63f7d365_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit"></a>
<!-- end oip-atom-subtitle.txt -->



</h3>
<p>
<a data-id="7298a802-a54a-44bb-a02d-d82d63f7d365_Body"  class="noteditable open-IncontextEditDialog_Text_Long in-context-edit"></a>

</p>
<!-- end oip-module-introduction.txt -->


<!-- THEBALL-CONTEXT-END:Introduction -->

</div>
<div class="multicolumnElement" style="padding-left:15px;padding-right:15px;">
    <p>
        <img src="../AaltoGlobalImpact.OIP/MediaContent/3fb4ad61-19f5-4adf-99e5-86a5a258f81e_320x240_crop.jpg" />
    </p>
    <p>Aalto UNICEF Finland Impact Project and Collaboration
In 2011, UNICEF Finland and Design Factory have entered into a collaboration to explore and support innovation for social impact. UNICEF Finland has made an effort to engage academia in a far more effective manner by bringing new possibilities to deliver greater support and impact for their mission and donors. This novel approach brings together highly motivated students with problem-solving skills in the fields of design, technology and business, with UNICEF Finland and Uganda personnel, including their respective partners. This alliance facilitates the creation of innovative solutions that will have a greater impact on the lives of the most vulnerable and marginalized children and their communities.
UNICEF Uganda country office has been identified as the key initial partner. During the academic year 2010-2011, the co-operation was formed and preparations were made for the second phase of the project. In 2011-2012, two pilot projects addressed real-life cases for UNICEF in the field of WASH (Water Sanitation and Hygiene).
PDP (Product Development Project) and IDBM (International Design Business Management) students teamed up with students from Makerere University (one of the oldest universities in Africa), to form a truly inter-disciplinary and multi-cultural team. The 15 strong team members have been supported by an immense network from their respective universities, UNICEF and other partners, resulting in ground breaking access and excellent development within the field of WASH. The students are nearing their course completion and will soon present their work. Plans are also in the works for a continuation of the great progress and development completed thus far, implementation in the field and and world of UNICEF being of high importance.</p>
</div>
<div>
	<div id="flowcontainer" class="thumbnails">
		
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImageGroupCollection -->



	</div>
	<br>
	
<script>
	$(function(){
		var $container = $('#flowcontainer');
		$container.isotope({
		itemSelector: '.oipimagecollection'
		});
	});
</script>
</div>
<div class="reading-pane-footer">
    <div class="meta">
        <!--
        using same <dl></dl> as in tiles
        -->
        <dl class="dl-horizontal date"><dt>on</dt><dd>1/1/0001 12:00:00 AM</dd></dl>
        <dl class="dl-horizontal author"><dt>by</dt><dd></dd></dl>
    </div>
    <div class="controls">
        <ul class="inline">
            <li>
                <form>
                    <i class="icon-bookmark"></i>
                    <input class="text" name="share_url" value="http://www.aaltoglobalimpact.org/www-public/oip-layout-landing.phtml?type=activity&id=693ee0b1-278c-4de1-9dbb-7e9befb1f13f">
                </form>
            </li>
        </ul>
    </div>
</div>


<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.Activity -->


