
<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.Blog -->

	<h2>
<!-- start oip-atom-subtitle.txt -->
<a data-id="b5037e1b-1725-4719-aaac-a25e8b6fe92a_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">Rahim Saatov</a>
<!-- end oip-atom-subtitle.txt -->



		<br>
		<small>
<!-- start oip-atom-subtitle.txt -->
<span class="small-before-after"/>"</span>
<a data-id="b5037e1b-1725-4719-aaac-a25e8b6fe92a_SubTitle"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit"></a>
<span class="small-before-after"/>"</span>
<!-- end oip-atom-subtitle.txt -->
</small>
	</h2>
</div>
<div class="multicolumnElement" style="padding-left:15px;padding-right:15px;">
    <p>
        <img src="../AaltoGlobalImpact.OIP/MediaContent/83b72867-73f7-46c0-bc1f-30504a454524_320x240_crop.jpg" />
    </p>
	<p>
		Rahim is the Resource Mobilization Manager. He has more than seven years of experience with tendering, management and coordination of large scale EU and MFA Finland development cooperation projects. He has worked within consultancy companies, universities and international organizations in Azerbaijan, South Africa and Finland. In 2010, Rahim has founded Pragman Consulting, and worked on assignments for different partners, including for Aalto University School of Business.<br><br>Rahim holds a MSSc degree (Political Science) with specialization in international development from the University of Jyväskylä, and Bachelor’s degree in International Business from Khazar University.<br><br>At Aalto Global Impact, he aims to bring together resources and individuals from academia, business and civil society to positively impact society and together create the changes that will bring us closer to our vision.<br>
	</p>
</div>
<div>
	<div id="flowcontainer" class="thumbnails">
		
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImageGroupCollection -->



	</div>
	<br>
	
<script>
    $(function(){
      var $container = $('#flowcontainer');
      $container.isotope({
        itemSelector: '.oipimagecollection'
      });
    });
</script>
</div>
<div class="reading-pane-footer">
    <div class="meta">
        <!--
        using same <dl></dl> as in tiles
        -->
        <dl class="dl-horizontal date"><dt>on</dt><dd>3/19/2013 11:15:44 AM</dd></dl>
        <dl class="dl-horizontal author"><dt>by</dt><dd>Aalto Global Impact</dd></dl>
    </div>
    <div class="controls">
        <ul class="inline">
            <li>
                <form>
                    <i class="icon-bookmark"></i>
                    <input class="text" name="share_url" value="http://www.aaltoglobalimpact.org/www-public/oip-layout-landing.phtml?type=news&id=b5037e1b-1725-4719-aaac-a25e8b6fe92a">
                </form>
            </li>
        </ul>
    </div>
</div>


<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.Blog -->


