
<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.Blog -->

	<h2>
<!-- start oip-atom-subtitle.txt -->
<a data-id="de514c87-4aad-424c-a1f5-4a01ae4c2f8c_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">Safe and Sustainable Sanitation Workshop</a>
<!-- end oip-atom-subtitle.txt -->



		<br>
		<small>
<!-- start oip-atom-subtitle.txt -->
<span class="small-before-after"/>"</span>
<a data-id="de514c87-4aad-424c-a1f5-4a01ae4c2f8c_SubTitle"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit"></a>
<span class="small-before-after"/>"</span>
<!-- end oip-atom-subtitle.txt -->
</small>
	</h2>
</div>
<div class="multicolumnElement" style="padding-left:15px;padding-right:15px;">
    <p>
        <img src="../AaltoGlobalImpact.OIP/MediaContent/c9a42847-bcb9-45fc-801b-335a7ed4e12f_320x240_crop.jpg" />
    </p>
	<p>
		<span lang="">
<p>The next pre-conference workshop Safe and Sustainable Sanitation is organized at Tampere Universty of Technology in August 20-22 prior to the 4th International Dry Toilet Conference.</p></span>
<span lang="">
<p>Workshop lectures are recorded and used on an online course Safe and Sustainable Sanitation. Students, who come to the workshop and wish to complete also the online course, pass only certain online modules and earn 5 ECTS credits altogether. The workshop is free of charge and UniPID students are welcome to participate.</p>
<p><span lang="">For more information and workshop registration please contact: maarit.sarkilahti@tut.fi, tuula.tuhkanen@tut.fi The deadline for registration is May 15th 2012.</span></p>
<span lang="">
<p><a href="http://demooip.aaltoglobalimpact.org/auth/grp/9798daca-afc4-4046-a99b-d0d88bb364e0/website/oip-group/www.drytoilet.org/dt2012/"><span lang="">www.drytoilet.org/dt2012/</span></a></p>
<p><a href="http://www.drytoilet.org/dt2012/Pdf/SSS_preliminary_program.pdf"><span lang="">http://www.drytoilet.org/dt2012/Pdf/SSS_preliminary_program.pdf</span></a><span lang=""> </span></p></span></span>
	</p>
</div>
<div>
	<div id="flowcontainer" class="thumbnails">
		
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImageGroupCollection -->



	</div>
	<br>
	
<script>
    $(function(){
      var $container = $('#flowcontainer');
      $container.isotope({
        itemSelector: '.oipimagecollection'
      });
    });
</script>
</div>
<div class="reading-pane-footer">
    <div class="meta">
        <!--
        using same <dl></dl> as in tiles
        -->
        <dl class="dl-horizontal date"><dt>on</dt><dd>11/17/2012 12:00:00 AM</dd></dl>
        <dl class="dl-horizontal author"><dt>by</dt><dd>Aalto Global Impact</dd></dl>
    </div>
    <div class="controls">
        <ul class="inline">
            <li>
                <form>
                    <i class="icon-bookmark"></i>
                    <input class="text" name="share_url" value="http://www.aaltoglobalimpact.org/www-public/oip-layout-landing.phtml?type=news&id=de514c87-4aad-424c-a1f5-4a01ae4c2f8c">
                </form>
            </li>
        </ul>
    </div>
</div>


<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.Blog -->


