
<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.Blog -->

	<h2>
<!-- start oip-atom-subtitle.txt -->
<a data-id="5b7b4d6b-8cfc-4fdb-bd62-cda4f09d3d1a_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">Riina Subra</a>
<!-- end oip-atom-subtitle.txt -->



		<br>
		<small>
<!-- start oip-atom-subtitle.txt -->
<span class="small-before-after"/>"</span>
<a data-id="5b7b4d6b-8cfc-4fdb-bd62-cda4f09d3d1a_SubTitle"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit"></a>
<span class="small-before-after"/>"</span>
<!-- end oip-atom-subtitle.txt -->
</small>
	</h2>
</div>
<div class="multicolumnElement" style="padding-left:15px;padding-right:15px;">
    <p>
        <img src="../AaltoGlobalImpact.OIP/MediaContent/8d1cdf3d-342a-4027-aad3-0da5eead0d21_320x240_crop.jpg" />
    </p>
	<p>
		Riina is the Foresight &amp; Advocacy Manager. During the past ten years, she has specialized in management work with international organisations, designing projects, strategies and partnerships for UNESCO and the United Nations Development Programme both in the field and in headquarters. Riina completed her MSocSc. in political science and philosophy at the University of Helsinki, and has a passion for multi-disciplinary research.<br><br>Through Aalto Global Impact, she aims to build collaborations where students and researchers from various disciplines can put their thoughts into practice around real-world problems to be solved.<br>
	</p>
</div>
<div>
	<div id="flowcontainer" class="thumbnails">
		
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImageGroupCollection -->



	</div>
	<br>
	
<script>
    $(function(){
      var $container = $('#flowcontainer');
      $container.isotope({
        itemSelector: '.oipimagecollection'
      });
    });
</script>
</div>
<div class="reading-pane-footer">
    <div class="meta">
        <!--
        using same <dl></dl> as in tiles
        -->
        <dl class="dl-horizontal date"><dt>on</dt><dd>3/19/2013 11:16:54 AM</dd></dl>
        <dl class="dl-horizontal author"><dt>by</dt><dd>Aalto Global Impact</dd></dl>
    </div>
    <div class="controls">
        <ul class="inline">
            <li>
                <form>
                    <i class="icon-bookmark"></i>
                    <input class="text" name="share_url" value="http://www.aaltoglobalimpact.org/www-public/oip-layout-landing.phtml?type=news&id=5b7b4d6b-8cfc-4fdb-bd62-cda4f09d3d1a">
                </form>
            </li>
        </ul>
    </div>
</div>


<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.Blog -->


