
<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.Blog -->

	<h2>
<!-- start oip-atom-subtitle.txt -->
<a data-id="a1ec4095-9960-4dbf-b8b9-343dd7d46d18_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">Lecture by Lee Bryant: Networked Innovation – Entrepreneurship for a Better Future</a>
<!-- end oip-atom-subtitle.txt -->



		<br>
		<small>
<!-- start oip-atom-subtitle.txt -->
<span class="small-before-after"/>"</span>
<a data-id="a1ec4095-9960-4dbf-b8b9-343dd7d46d18_SubTitle"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit"></a>
<span class="small-before-after"/>"</span>
<!-- end oip-atom-subtitle.txt -->
</small>
	</h2>
</div>
<div class="multicolumnElement" style="padding-left:15px;padding-right:15px;">
    <p>
        <img src="../AaltoGlobalImpact.OIP/MediaContent/f2045e65-608b-45f8-8676-52ef15ef0ceb_320x240_crop.jpg" />
    </p>
	<p>
		We are pleased to invite you to our next event:<br>Networked Innovation – Entrepreneurship for a Better Future, lecture by Lee Bryant, Managing Director, Dachis Group. Please see more information and link to registration in the <a target="_blank" title="" href="http://www.aaltoglobalimpact.org/file_download/3/Guest+Lecture+by+Lee+Bryant+on+16.10+-+Invitation.pdf">invitation</a>.<br>
	</p>
</div>
<div>
	<div id="flowcontainer" class="thumbnails">
		
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImageGroupCollection -->



	</div>
	<br>
	<iframe width="560" height="315" src="http://www.youtube.com/embed/yDO-lAqsrzg" frameborder="0" allowfullscreen></iframe>
<script>
    $(function(){
      var $container = $('#flowcontainer');
      $container.isotope({
        itemSelector: '.oipimagecollection'
      });
    });
</script>
</div>
<div class="reading-pane-footer">
    <div class="meta">
        <!--
        using same <dl></dl> as in tiles
        -->
        <dl class="dl-horizontal date"><dt>on</dt><dd>10/16/2012 11:13:26 AM</dd></dl>
        <dl class="dl-horizontal author"><dt>by</dt><dd>Aalto Global Impact</dd></dl>
    </div>
    <div class="controls">
        <ul class="inline">
            <li>
                <form>
                    <i class="icon-bookmark"></i>
                    <input class="text" name="share_url" value="http://www.aaltoglobalimpact.org/www-public/oip-layout-landing.phtml?type=news&id=a1ec4095-9960-4dbf-b8b9-343dd7d46d18">
                </form>
            </li>
        </ul>
    </div>
</div>


<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.Blog -->


