
<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.Blog -->

	<h2>
<!-- start oip-atom-subtitle.txt -->
<a data-id="9ec49203-fd65-4fed-92c0-416a3f9b794e_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">Social Impact through Creative Design - seminar</a>
<!-- end oip-atom-subtitle.txt -->



		<br>
		<small>
<!-- start oip-atom-subtitle.txt -->
<span class="small-before-after"/>"</span>
<a data-id="9ec49203-fd65-4fed-92c0-416a3f9b794e_SubTitle"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit"></a>
<span class="small-before-after"/>"</span>
<!-- end oip-atom-subtitle.txt -->
</small>
	</h2>
</div>
<div class="multicolumnElement" style="padding-left:15px;padding-right:15px;">
    <p>
        <img src="../AaltoGlobalImpact.OIP/MediaContent/698d46c9-e044-40f1-a6bb-ed1bc952ab77_320x240_crop.jpg" />
    </p>
	<p>
		<p>The role of design in the society is rapidly developing to meet global and local challenges better. Social Impact through Creative Design seminar presents how different Aalto University initiatives meet these challenges. Two international guest speakers will give an introduction to design for social innovation - Hrridaysh Deshpande´s lecture will take the participants through the distinct aspects of the progress and challenges in India that lie ahead. Virginia Tassinari from Belgia will zoom up into the philosophical aspects of social innovation. Aalto University representatives will present examples and outcomes of various projects and courses which used creative design to solve global challenges. The seminar is presented by Aalto Global Impact and Master`s Degree programme in Creative Sustainability.</p>
<p>&nbsp;</p>
<p>Time: Tuesday, 22/5 at 12.15 pm - 5:00 pm. </p>
<p>Venue: Master`s of Arts exhibition hall, Rantamakasiini L3</p>
<p>Tyynenmerenkatu 6 (ex. Hietasaarenkuja 6), Jätkasaari </p>
<p>(Bus lines 15 A from Elielinaukio, 15 from Ruoholahti and Tram lines 6 and 8) </p>
<p>&nbsp;</p>
<p>PROGRAMME </p>
<p>12:15 - 12:20 Opening </p>
<p>12:20 – 1:15 India: Large &amp; Small and Design in India,</p>
<p>Hrridaysh Deshpande, Director, DYPDC Center for Automotive Research &amp; Studies</p>
<p>1:15 - 2:00 Social innovation and Ockham's razor, Virginia Tassinari, Media en Design Academie, KHLiM</p>
<p>2:00 - 2:20 Aalto Global Impact and Inclusive Businesses Network, Teija Lehtonen, Aalto Global Impact </p>
<p>2:20 - 2:40 Aalto - UNICEF Finland Collaboration, Andy Clutterbuck, Aalto Global Impact </p>
<p>2:40 - 3:00 coffee break</p>
<p>Aalto University student project presentations:</p>
<p>3:00 - 3:20 Design for A Social Change - GloCal project, Sujil Kodathoor</p>
<p>3:20 - 3:40 Mozambique project - business models for local producers, Oparaocha Gospel</p>
<p>3:40 - 4:00 Design for Extreme affordability - pyrolytic stove in Kenya and EduAid low cost lighting solution, Rahul Abhisek and Brenda Vertiz</p>
<p>4:00 - 4:20 How to Change the World -Junailijankuja 5: Improving housing for students by students, Brenda Vertiz,</p>
<p>4:20 - 5:00 discussion</p>
<p>Event is free, no registration</p>
<p>Further information: </p>
<p>Tiina Laurila </p>
<p><a href="tel:%2B358%2050%204433977">+358 50 4433977</a> </p>
<p><a href="mailto:tiina.laurila@aalto.fi">tiina.laurila@aalto.fi</a></p><span lang="">
<p align="justify">&nbsp;</p>
<p><a title="Contact MoA" href="http://moa.aalto.fi/2012/en/contact/" target="_blank">Contact MoA&nbsp;http://moa.aalto.fi/2012/en/contact/</a> </p></span><span lang="">
<p>　</p></span>
	</p>
</div>
<div>
	<div id="flowcontainer" class="thumbnails">
		
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImageGroupCollection -->



	</div>
	<br>
	
<script>
    $(function(){
      var $container = $('#flowcontainer');
      $container.isotope({
        itemSelector: '.oipimagecollection'
      });
    });
</script>
</div>
<div class="reading-pane-footer">
    <div class="meta">
        <!--
        using same <dl></dl> as in tiles
        -->
        <dl class="dl-horizontal date"><dt>on</dt><dd>11/2/2012 10:19:04 AM</dd></dl>
        <dl class="dl-horizontal author"><dt>by</dt><dd>Aalto Global Impact</dd></dl>
    </div>
    <div class="controls">
        <ul class="inline">
            <li>
                <form>
                    <i class="icon-bookmark"></i>
                    <input class="text" name="share_url" value="http://www.aaltoglobalimpact.org/www-public/oip-layout-landing.phtml?type=news&id=9ec49203-fd65-4fed-92c0-416a3f9b794e">
                </form>
            </li>
        </ul>
    </div>
</div>


<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.Blog -->


