
<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.Activity -->

<h2><a data-id="51c0a82a-5dc9-4e8e-9012-7f2631f73708_ActivityName" title="Edit Activity Name" class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">Aalto LAB Mexico, Design for sustainability in the Maya community</a>

</h2>

<!-- THEBALL-CONTEXT-OBJECT-BEGIN:Introduction -->

<!-- oip-module-introduction.txt -->
<h3>

<!-- start oip-atom-subtitle.txt -->
<a data-id="9492be0a-f4f0-452d-9b05-ea332c297aac_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit"></a>
<!-- end oip-atom-subtitle.txt -->



</h3>
<p>
<a data-id="9492be0a-f4f0-452d-9b05-ea332c297aac_Body"  class="noteditable open-IncontextEditDialog_Text_Long in-context-edit"></a>

</p>
<!-- end oip-module-introduction.txt -->


<!-- THEBALL-CONTEXT-END:Introduction -->

</div>
<div class="multicolumnElement" style="padding-left:15px;padding-right:15px;">
    <p>
        <img src="../AaltoGlobalImpact.OIP/MediaContent/69d8073f-114c-4c3a-a8ba-ef2c4112191f_320x240_crop.jpg" />
    </p>
    <p>Aalto LAB Mexico is an interdisciplinary project that aims at sustainable livelihood and social change through design elements. The project was started in August, 2012 and it is the Mexican branch of the wider Aalto LAB  framework, started in Shanghai, 2010. Aalto LAB Mexico comprises two cross-disciplinary teams, one located in the Finnish capital area, consisting of students from Aalto University, and the other located in Mexico City, consisting of students from Universidad Nacional Autónoma de México and Instituto Tecnológico y de Estudios Superiores de Monterrey Campus Ciudad de México.

The two project teams collaborate with the Mayan community called 20 de Noviembre, near the city of Xpujil in the Yucatan peninsula, Mexico. The team works towards creating long-term sustainable solutions that arise from the needs of the Mayan community. The project hence involves working both in Helsinki/Mexico City and within the community. The first two-week field period is in November, 2012. This period includes the investigation and presentation of the possibilities for further implementation of tools and workshops.

Additionally, Aalto LAB Mexico aims to learn lessons from the community, and, it pursues to affect the local stakeholders both in Finland and Mexico by addressing the questions of sustainability and development in media and events.

Join Aalto Lab Mexico's facebook page to hear more updates.</p>
</div>
<div>
	<div id="flowcontainer" class="thumbnails">
		
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImageGroupCollection -->



	</div>
	<br>
	
<script>
	$(function(){
		var $container = $('#flowcontainer');
		$container.isotope({
		itemSelector: '.oipimagecollection'
		});
	});
</script>
</div>
<div class="reading-pane-footer">
    <div class="meta">
        <!--
        using same <dl></dl> as in tiles
        -->
        <dl class="dl-horizontal date"><dt>on</dt><dd>1/2/2013 12:00:00 AM</dd></dl>
        <dl class="dl-horizontal author"><dt>by</dt><dd></dd></dl>
    </div>
    <div class="controls">
        <ul class="inline">
            <li>
                <form>
                    <i class="icon-bookmark"></i>
                    <input class="text" name="share_url" value="http://www.aaltoglobalimpact.org/www-public/oip-layout-landing.phtml?type=activity&id=51c0a82a-5dc9-4e8e-9012-7f2631f73708">
                </form>
            </li>
        </ul>
    </div>
</div>


<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.Activity -->


