
<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.Blog -->

	<h2>
<!-- start oip-atom-subtitle.txt -->
<a data-id="566a6297-594d-4c9d-9fae-f730423fe986_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">Aalto student talk</a>
<!-- end oip-atom-subtitle.txt -->



		<br>
		<small>
<!-- start oip-atom-subtitle.txt -->
<span class="small-before-after"/>"</span>
<a data-id="566a6297-594d-4c9d-9fae-f730423fe986_SubTitle"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit"></a>
<span class="small-before-after"/>"</span>
<!-- end oip-atom-subtitle.txt -->
</small>
	</h2>
</div>
<div class="multicolumnElement" style="padding-left:15px;padding-right:15px;">
    <p>
        <img src="../AaltoGlobalImpact.OIP/MediaContent/111c0a6f-cce5-4fa8-bdf6-8eff32a145ac_320x240_crop.jpg" />
    </p>
	<p>
		<span lang=""> 
<p>Delegation from Delft University of Technology, the Netherlands visited Aalto University in June. The delegation was in search to understand Aalto's approaches of social responsiveness and engagement. During the visit the guests compiled a video asking students why they are interested in social impact and how Aalto promotes and supports students' interests in such projects. See here how some of the Aalto students explain their involvement in fascinating examples of social impact initiatives: <a href="http://www.youtube.com/watch?v=zELlx1qtRjc">http://www.youtube.com/watch?v=zELlx1qtRjc</a></p></span>
	</p>
</div>
<div>
	<div id="flowcontainer" class="thumbnails">
		
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImageGroupCollection -->



	</div>
	<br>
	<iframe width="560" height="315" src="http://www.youtube.com/embed/zELlx1qtRjc" frameborder="0" allowfullscreen></iframe>
<script>
    $(function(){
      var $container = $('#flowcontainer');
      $container.isotope({
        itemSelector: '.oipimagecollection'
      });
    });
</script>
</div>
<div class="reading-pane-footer">
    <div class="meta">
        <!--
        using same <dl></dl> as in tiles
        -->
        <dl class="dl-horizontal date"><dt>on</dt><dd>11/2/2012 1:33:13 PM</dd></dl>
        <dl class="dl-horizontal author"><dt>by</dt><dd>Aalto Global Impact</dd></dl>
    </div>
    <div class="controls">
        <ul class="inline">
            <li>
                <form>
                    <i class="icon-bookmark"></i>
                    <input class="text" name="share_url" value="http://www.aaltoglobalimpact.org/www-public/oip-layout-landing.phtml?type=news&id=566a6297-594d-4c9d-9fae-f730423fe986">
                </form>
            </li>
        </ul>
    </div>
</div>


<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.Blog -->


