
<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.Blog -->

	<h2>
<!-- start oip-atom-subtitle.txt -->
<a data-id="bcc9d0ed-b260-4ca9-b29d-e8bc30ea5b7f_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">Andrew Clutterbuck</a>
<!-- end oip-atom-subtitle.txt -->



		<br>
		<small>
<!-- start oip-atom-subtitle.txt -->
<span class="small-before-after"/>"</span>
<a data-id="bcc9d0ed-b260-4ca9-b29d-e8bc30ea5b7f_SubTitle"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit"></a>
<span class="small-before-after"/>"</span>
<!-- end oip-atom-subtitle.txt -->
</small>
	</h2>
</div>
<div class="multicolumnElement" style="padding-left:15px;padding-right:15px;">
    <p>
        <img src="../AaltoGlobalImpact.OIP/MediaContent/f1e88668-3526-467c-a9ef-c679abe2f118_320x240_crop.jpg" />
    </p>
	<p>
		Andrew is the Coach &amp; Community Manager. The past 4 years, Andrew has worked on the development of the Aalto Design Factory model and the interactions within the community at large. His role as the Aalto Design Factory Coach has been key in bridging the gap between industry and academia through interaction.<br><br>Working closely with the internationalization of the Aalto Design Factory and developing relations/collaborations with operational partners, most recently the collaboration between UNICEF Finland and Aalto University. Andrew is an advocate for Passion Based Learning and interdisciplinary co-creation, with fun being a crucial factor. He hopes to build and strengthen the Aalto Global Impact community through such actions. <br>
	</p>
</div>
<div>
	<div id="flowcontainer" class="thumbnails">
		
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImageGroupCollection -->



	</div>
	<br>
	
<script>
    $(function(){
      var $container = $('#flowcontainer');
      $container.isotope({
        itemSelector: '.oipimagecollection'
      });
    });
</script>
</div>
<div class="reading-pane-footer">
    <div class="meta">
        <!--
        using same <dl></dl> as in tiles
        -->
        <dl class="dl-horizontal date"><dt>on</dt><dd>3/19/2013 11:16:28 AM</dd></dl>
        <dl class="dl-horizontal author"><dt>by</dt><dd>Aalto Global Impact</dd></dl>
    </div>
    <div class="controls">
        <ul class="inline">
            <li>
                <form>
                    <i class="icon-bookmark"></i>
                    <input class="text" name="share_url" value="http://www.aaltoglobalimpact.org/www-public/oip-layout-landing.phtml?type=news&id=bcc9d0ed-b260-4ca9-b29d-e8bc30ea5b7f">
                </form>
            </li>
        </ul>
    </div>
</div>


<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.Blog -->


