
<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.Blog -->

	<h2>
<!-- start oip-atom-subtitle.txt -->
<a data-id="045e9d00-74b7-4ccb-b503-936362862cc5_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">Aalto - World Bank partnership: Training Program on Innovation Policy for ICT</a>
<!-- end oip-atom-subtitle.txt -->



		<br>
		<small>
<!-- start oip-atom-subtitle.txt -->
<span class="small-before-after"/>"</span>
<a data-id="045e9d00-74b7-4ccb-b503-936362862cc5_SubTitle"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">10-14 September, 2012</a>
<span class="small-before-after"/>"</span>
<!-- end oip-atom-subtitle.txt -->
</small>
	</h2>
</div>
<div class="multicolumnElement" style="padding-left:15px;padding-right:15px;">
    <p>
        <img src="../AaltoGlobalImpact.OIP/MediaContent/b03ce5fa-c57d-40e5-bb83-2be19d36d0ac_320x240_crop.jpg" />
    </p>
	<p>
		<span lang="EN"> 
<p align="justify">Aalto Global Impact hosted two training workshops "Training Program on Innovation Policy for ICT" in 2012 in Helsinki, Finland. The main objective of the workshops was to develop the learning of participating decision-makers on strategic innovation policy in the field of ICT, in a multidisciplinary and multicultural setting. The approach is to engage the decision-makers in a hands-on, participatory and real-life case study analysis that involve also prototyping and testing of concepts, business models and service designs.</p>
<p align="justify"></p>
<p align="justify">During the first workshop (4-9 June 2012) participants came from Morocco, Tunisia, Egypt, Lebanon, Moldova, Armenia, Georgia and Mexico, as well as four senior officials from the World Bank headquarters in Washington DC. During the second workshop (10-14 September 2012), 15 senior policymakers and representatives of key governmental organizations from Burkina Faso, Ghana, India, Kenya, Philippines, Uganda, South Africa, and Tanzania, as well as 5 senior officials from the World Bank headquarters and one from country office in Senegal participated in the 5-days long intensive training course. </p>

<p>The trainings were designed and facilitated by Professor Mikko Koria, with the support from Aalto Global Impact. During each work shop, <span lang="">over 20 speakers from different Finnish organizations shared their insights with the participants. </span><span lang="EN">The work shops were part of the piloting initiative by The World Bank ICT Sector Unit, infoDev, the Ministry for Foreign Affairs of Finland and Aalto University. </span><span lang="">For more information, contact Rahim Saatov, who worked closely with the organization of the trainings. </span></p></span>
	</p>
</div>
<div>
	<div id="flowcontainer" class="thumbnails">
		
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImageGroupCollection -->



	</div>
	<br>
	
<script>
    $(function(){
      var $container = $('#flowcontainer');
      $container.isotope({
        itemSelector: '.oipimagecollection'
      });
    });
</script>
</div>
<div class="reading-pane-footer">
    <div class="meta">
        <!--
        using same <dl></dl> as in tiles
        -->
        <dl class="dl-horizontal date"><dt>on</dt><dd>10/23/2012 2:33:24 PM</dd></dl>
        <dl class="dl-horizontal author"><dt>by</dt><dd>Aalto Global Impact</dd></dl>
    </div>
    <div class="controls">
        <ul class="inline">
            <li>
                <form>
                    <i class="icon-bookmark"></i>
                    <input class="text" name="share_url" value="http://www.aaltoglobalimpact.org/www-public/oip-layout-landing.phtml?type=news&id=045e9d00-74b7-4ccb-b503-936362862cc5">
                </form>
            </li>
        </ul>
    </div>
</div>


<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.Blog -->


