
<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.Activity -->

<h2><a data-id="dba2da4d-6e31-4ecc-b5c4-0b8491d6b28c_ActivityName" title="Edit Activity Name" class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">GLOCAL: m-Nutrition for Infant Health – Global Mobile Platform Tested Locally in Rural India</a>

</h2>

<!-- THEBALL-CONTEXT-OBJECT-BEGIN:Introduction -->

<!-- oip-module-introduction.txt -->
<h3>

<!-- start oip-atom-subtitle.txt -->
<a data-id="85bd4b5c-40cb-430e-b262-a63e21aaa328_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit"></a>
<!-- end oip-atom-subtitle.txt -->



</h3>
<p>
<a data-id="85bd4b5c-40cb-430e-b262-a63e21aaa328_Body"  class="noteditable open-IncontextEditDialog_Text_Long in-context-edit"></a>

</p>
<!-- end oip-module-introduction.txt -->


<!-- THEBALL-CONTEXT-END:Introduction -->

</div>
<div class="multicolumnElement" style="padding-left:15px;padding-right:15px;">
    <p>
        <img src="../AaltoGlobalImpact.OIP/MediaContent/35bdf23d-7774-4051-9e41-42fa34997179_320x240_crop.jpg" />
    </p>
    <p>High infant mortality and health risks in India are linked to inappropriate feeding practices especially during the first two years of a child’s life. To address persistent challenges in feeding practices, Professor Marja Mutanen and her team from the University of Helsinki started an innovative Tekes-funded m-Health project – GloCal – in 2011. This project was further developed in collaboration with Creative Sustainability students from Aalto University. GloCal brings together nutritionists, anthropologists, e-learning experts, private Finnish companies, and local NGOs in India.
</p>
</div>
<div>
	<div id="flowcontainer" class="thumbnails">
		
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImageGroupCollection -->



	</div>
	<br>
	
<script>
	$(function(){
		var $container = $('#flowcontainer');
		$container.isotope({
		itemSelector: '.oipimagecollection'
		});
	});
</script>
</div>
<div class="reading-pane-footer">
    <div class="meta">
        <!--
        using same <dl></dl> as in tiles
        -->
        <dl class="dl-horizontal date"><dt>on</dt><dd>1/1/0001 12:00:00 AM</dd></dl>
        <dl class="dl-horizontal author"><dt>by</dt><dd></dd></dl>
    </div>
    <div class="controls">
        <ul class="inline">
            <li>
                <form>
                    <i class="icon-bookmark"></i>
                    <input class="text" name="share_url" value="http://www.aaltoglobalimpact.org/www-public/oip-layout-landing.phtml?type=activity&id=dba2da4d-6e31-4ecc-b5c4-0b8491d6b28c">
                </form>
            </li>
        </ul>
    </div>
</div>


<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.Activity -->


