
<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.Blog -->

	<h2>
<!-- start oip-atom-subtitle.txt -->
<a data-id="64937264-b94b-4746-95b2-27dce2545759_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">Anne Badan</a>
<!-- end oip-atom-subtitle.txt -->



		<br>
		<small>
<!-- start oip-atom-subtitle.txt -->
<span class="small-before-after"/>"</span>
<a data-id="64937264-b94b-4746-95b2-27dce2545759_SubTitle"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit"></a>
<span class="small-before-after"/>"</span>
<!-- end oip-atom-subtitle.txt -->
</small>
	</h2>
</div>
<div class="multicolumnElement" style="padding-left:15px;padding-right:15px;">
    <p>
        <img src="../AaltoGlobalImpact.OIP/MediaContent/636b4940-73e6-4ab5-a98f-95935b3b722c_320x240_crop.jpg" />
    </p>
	<p>
		Anne is the Strategy &amp; Partnerships Manager. She has more than 16 years of international experience in marketing and business development. Her expertise is in developing large-scale partnerships and new business opportunities in challenging markets. Her clients ranged from top Fortune 500 companies, to governments and international institutions.<br><br>For the past 5 years, Anne has been designing sustainable philanthropic/social impact programmes,working with philanthropists, companies and institutions. She created A2B Philanthropy in 2008 and founded Aalto Social Impact in 2009. She designed and tutored various courses related to sustainability and societal impact for Aalto University. Anne holds an M.A. in International Relations from the Graduate Institute of International and Development Studies (GIIDS) in Geneva, Switzerland and a certificate on Corporate Social Responsibility from Aalto School of Economics.<br>
	</p>
</div>
<div>
	<div id="flowcontainer" class="thumbnails">
		
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImageGroupCollection -->



	</div>
	<br>
	
<script>
    $(function(){
      var $container = $('#flowcontainer');
      $container.isotope({
        itemSelector: '.oipimagecollection'
      });
    });
</script>
</div>
<div class="reading-pane-footer">
    <div class="meta">
        <!--
        using same <dl></dl> as in tiles
        -->
        <dl class="dl-horizontal date"><dt>on</dt><dd>3/19/2013 11:17:17 AM</dd></dl>
        <dl class="dl-horizontal author"><dt>by</dt><dd>Aalto Global Impact</dd></dl>
    </div>
    <div class="controls">
        <ul class="inline">
            <li>
                <form>
                    <i class="icon-bookmark"></i>
                    <input class="text" name="share_url" value="http://www.aaltoglobalimpact.org/www-public/oip-layout-landing.phtml?type=news&id=64937264-b94b-4746-95b2-27dce2545759">
                </form>
            </li>
        </ul>
    </div>
</div>


<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.Blog -->


