
<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.Blog -->

	<h2>
<!-- start oip-atom-subtitle.txt -->
<a data-id="7cc8d059-5698-45de-bf2e-461680b7d388_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">India and Sri Lanka: Rapid Development for Inclusive Innovation</a>
<!-- end oip-atom-subtitle.txt -->



		<br>
		<small>
<!-- start oip-atom-subtitle.txt -->
<span class="small-before-after"/>"</span>
<a data-id="7cc8d059-5698-45de-bf2e-461680b7d388_SubTitle"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit"></a>
<span class="small-before-after"/>"</span>
<!-- end oip-atom-subtitle.txt -->
</small>
	</h2>
</div>
<div class="multicolumnElement" style="padding-left:15px;padding-right:15px;">
    <p>
        <img src="../AaltoGlobalImpact.OIP/MediaContent/abff8674-595f-4040-8a2e-24959390daeb_320x240_crop.jpg" />
    </p>
	<p>
		<SPAN lang=""> 
<P>This multi-disciplinary and collaborative research project focuses on finding the central mechanics and concepts that are needed for creating sustainable wellbeing businesses in the base of the pyramid (BoP) markets. The project concentrates especially in new organizational models and use of technological advances as well as innovation strategies in co-creating vibrant business ecosystems where Finnish companies together with the local actors at the BoP markets create value. </P>
<P>&nbsp;</P>
<P>Understanding the mechanics and needs for successful engagement in the BoP markets can revolutionize Finnish companies participation in the global value networks. The objectives of this project are:</P>
<UL>
<LI>
<DIV>Generation of dynamics and deeper understanding of multi-stakeholder inclusive innovation and co-creation processes at the BoP.</DIV></LI>
<LI>Analysis of the central mechanics of a ground breaking business ecosystem pilot in the sector of health and wellbeing.</LI>
<LI>
<DIV>Theoretically founded roadmap for creating profitable businesses in the intersection of innovation ecosystems of Finland and BoP markets.</DIV></LI></UL>
<P>&nbsp;</P>
<P>Funding for this project is sought from Tekes and Finnish companies.</P></SPAN>
	</p>
</div>
<div>
	<div id="flowcontainer" class="thumbnails">
		
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImageGroupCollection -->



	</div>
	<br>
	
<script>
    $(function(){
      var $container = $('#flowcontainer');
      $container.isotope({
        itemSelector: '.oipimagecollection'
      });
    });
</script>
</div>
<div class="reading-pane-footer">
    <div class="meta">
        <!--
        using same <dl></dl> as in tiles
        -->
        <dl class="dl-horizontal date"><dt>on</dt><dd>11/2/2012 1:03:39 PM</dd></dl>
        <dl class="dl-horizontal author"><dt>by</dt><dd>Aalto Global Impact</dd></dl>
    </div>
    <div class="controls">
        <ul class="inline">
            <li>
                <form>
                    <i class="icon-bookmark"></i>
                    <input class="text" name="share_url" value="http://www.aaltoglobalimpact.org/www-public/oip-layout-landing.phtml?type=news&id=7cc8d059-5698-45de-bf2e-461680b7d388">
                </form>
            </li>
        </ul>
    </div>
</div>


<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.Blog -->


