
<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.Blog -->

	<h2>
<!-- start oip-atom-subtitle.txt -->
<a data-id="33b68341-3c2b-44ee-9bd6-6c433580d089_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">LEARN/SHARE: Commercialization and Scaling up Inclusive Businesses in Emerging Markets</a>
<!-- end oip-atom-subtitle.txt -->



		<br>
		<small>
<!-- start oip-atom-subtitle.txt -->
<span class="small-before-after"/>"</span>
<a data-id="33b68341-3c2b-44ee-9bd6-6c433580d089_SubTitle"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">Exploring opportunities and practices for success </a>
<span class="small-before-after"/>"</span>
<!-- end oip-atom-subtitle.txt -->
</small>
	</h2>
</div>
<div class="multicolumnElement" style="padding-left:15px;padding-right:15px;">
    <p>
        <img src="../AaltoGlobalImpact.OIP/MediaContent/c2544cea-6618-48ed-876c-f22d699a6376_320x240_crop.jpg" />
    </p>
	<p>
		<SPAN lang="">
<P>This one-day workshop focused on the practical needs and opportunities of companies that aim to create new, profitable businesses in emerging markets while empowering local communities and reducing poverty.</P>
<P>&nbsp;</P>
<P>Under the framework of the Base of the Pyramid approach, we discussed examples of how the application of a market approach has contributed to poverty reduction through the development of products and services for low-income markets.</P>
<P>&nbsp;</P>
<P>Participants from Danone Poland, RLabs/Mxit Reach South Africa and Nokia provided concrete business examples of product development and commercialization, and Minna Halme, Professor of Corporate Responsibility at Aalto University highlighted success factors in BOP business approaches, based on examples from Grunfors Lifelink, Cemex, ITC eChoupal and MyC4 among others.</P>
<P>&nbsp;</P>
<P>In the afternoon's workshops, we explored and modeled the best opportunities and practices for success. The event is part of a wider BOP Service initiative entitled " Sustainable and user-driven innovation at the BOP market", coordinated by Aalto University and funded by Tekes, the Finnish Ministry of Employment and the Economy, the Ministry for Foreign Affairs, the Confederation of Finnish Industries and Finpro.</P>
<P>&nbsp;</P>
<P>In addition to Finnish stakeholders, participants from India, Sri Lanka, Nepal, South Africa, Kenya, Tanzania, Mozambique, Poland, Netherlands and the United States attended the workshop.</P>
<P>The program of the workshop, as well as all the documentation before and after the event can be found in our "Inclusive Businesses" group on Linked-in.</P>
<P>&nbsp;</P>
<P>For more information, please contact:</P>
<P>Teija Lehtonen, Director, Aalto Global Impact, teija.lehtonen(at)aalto.fi</P>
<P>&nbsp;</P>
<P>Date: Friday 20th April, 2012 Time:08.30 - 16.00 Place: Finpro, Porkkalankatu 1, Helsinki </P></SPAN>
	</p>
</div>
<div>
	<div id="flowcontainer" class="thumbnails">
		
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImageGroupCollection -->



	</div>
	<br>
	
<script>
    $(function(){
      var $container = $('#flowcontainer');
      $container.isotope({
        itemSelector: '.oipimagecollection'
      });
    });
</script>
</div>
<div class="reading-pane-footer">
    <div class="meta">
        <!--
        using same <dl></dl> as in tiles
        -->
        <dl class="dl-horizontal date"><dt>on</dt><dd>11/2/2012 10:19:50 AM</dd></dl>
        <dl class="dl-horizontal author"><dt>by</dt><dd>Aalto Global Impact</dd></dl>
    </div>
    <div class="controls">
        <ul class="inline">
            <li>
                <form>
                    <i class="icon-bookmark"></i>
                    <input class="text" name="share_url" value="http://www.aaltoglobalimpact.org/www-public/oip-layout-landing.phtml?type=news&id=33b68341-3c2b-44ee-9bd6-6c433580d089">
                </form>
            </li>
        </ul>
    </div>
</div>


<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.Blog -->


