
<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.Blog -->

	<h2>
<!-- start oip-atom-subtitle.txt -->
<a data-id="48df3178-928b-4ad4-938a-c9567d99b7b7_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">Aalto Global Impact newsletter December 2012</a>
<!-- end oip-atom-subtitle.txt -->



		<br>
		<small>
<!-- start oip-atom-subtitle.txt -->
<span class="small-before-after"/>"</span>
<a data-id="48df3178-928b-4ad4-938a-c9567d99b7b7_SubTitle"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">Please download our December 2012 newsletter.</a>
<span class="small-before-after"/>"</span>
<!-- end oip-atom-subtitle.txt -->
</small>
	</h2>
</div>
<div class="multicolumnElement" style="padding-left:15px;padding-right:15px;">
    <p>
        <img src="../AaltoGlobalImpact.OIP/MediaContent/201bc2a7-d77f-4562-83a2-1fdd7bb9f157_320x240_crop.jpg" />
    </p>
	<p>
		<span lang="">
<p>Please see here our <a target="_blank" title="Newsletter December" href="http://www.aaltoglobalimpact.org/file_download/9/Aalto+Global+Impact+newsletter_December+2012.pdf%20">December 2012 newsletter</a>.</p>

<p>If you are interested in recieving our newsletters delivered to your email address, please subscribe to Aalto Global Impact mailing list through this <a target="_blank" title="" href="https://list.aalto.fi/mailman/listinfo/aaltoglobalimpact">link</a>. </p>

<p>Aalto Global Impact team wishes you and your families a happy holiday season!</p><p>http://www.aaltoglobalimpact.org/file_download/9/Aalto+Global+Impact+newsletter_December+2012.pdf&nbsp;</p><p>https://list.aalto.fi/mailman/listinfo/aaltoglobalimpact<br></p></span>
	</p>
</div>
<div>
	<div id="flowcontainer" class="thumbnails">
		
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImageGroupCollection -->



	</div>
	<br>
	<iframe src="http://issuu.com/aaltoglobalimpact/docs/aginewsletterdec2012?mode=window" width="525" height="364"></iframe>
<script>
    $(function(){
      var $container = $('#flowcontainer');
      $container.isotope({
        itemSelector: '.oipimagecollection'
      });
    });
</script>
</div>
<div class="reading-pane-footer">
    <div class="meta">
        <!--
        using same <dl></dl> as in tiles
        -->
        <dl class="dl-horizontal date"><dt>on</dt><dd>12/17/2012 1:02:03 PM</dd></dl>
        <dl class="dl-horizontal author"><dt>by</dt><dd>Aalto Global Impact</dd></dl>
    </div>
    <div class="controls">
        <ul class="inline">
            <li>
                <form>
                    <i class="icon-bookmark"></i>
                    <input class="text" name="share_url" value="http://www.aaltoglobalimpact.org/www-public/oip-layout-landing.phtml?type=news&id=48df3178-928b-4ad4-938a-c9567d99b7b7">
                </form>
            </li>
        </ul>
    </div>
</div>


<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.Blog -->


