
<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.Activity -->

<h2><a data-id="409bf342-57d8-4e8e-9094-ffd5b30e3e67_ActivityName" title="Edit Activity Name" class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">Tanzania: Community and market improvement projects</a>

</h2>

<!-- THEBALL-CONTEXT-OBJECT-BEGIN:Introduction -->

<!-- oip-module-introduction.txt -->
<h3>

<!-- start oip-atom-subtitle.txt -->
<a data-id="bb947f43-b352-45fa-9c9e-02edb18908c6_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit"></a>
<!-- end oip-atom-subtitle.txt -->



</h3>
<p>
<a data-id="bb947f43-b352-45fa-9c9e-02edb18908c6_Body"  class="noteditable open-IncontextEditDialog_Text_Long in-context-edit"></a>

</p>
<!-- end oip-module-introduction.txt -->


<!-- THEBALL-CONTEXT-END:Introduction -->

</div>
<div class="multicolumnElement" style="padding-left:15px;padding-right:15px;">
    <p>
        <img src="../AaltoGlobalImpact.OIP/MediaContent/8a38ddd0-b93f-4983-85dd-f7c6f74eca9c_320x240_crop.jpg" />
    </p>
    <p>Real impact requires commitment, community embeddedness and hard work. Several Aalto project courses have come together to establish a joint field project in Tanzania. Multidisciplinary student teams will support the development and realization of community and market improvement projects. These projects are initiated and run by community groups, which are organized into a network called Tanzanian Federation of the Urban Poor, TFUP. The idea is that local people are best suited to identify both problems and solutions.
This year, the students together with the communities, will work on cases such as solid waste management – exploring possibilities for recycling, new product development, biogas and improved livelihood. The projects also include planning a market and a social housing scheme in a new settlement area, addressing issues of affordable housing and livelihood creation. The aim is for these projects to be realized by the communities. The project work is an opportunity for students to apply their professional skills in a real-world-challenge, as well as an intense learning experience about the realities of the Global South. The learning process is mutual as the students and locals work together. Through the network of the TFUP, reaching more than 8,500 people, the possible ideas and innovations generated can spread to other communities in Tanzania and internationally.
This education forms part of the Creative Sustainability Masters Program, and focuses on participatory planning and user-driven innovation. Project typically range from slum environment upgrading, small business and market development, and low-cost housing planning and construction. Particular focus is placed on considerations of sustainability, ethics and systems thinking. The first set of students will travel to Tanzania in March 2013, and they will work on the project the whole spring term. Some students may also seek to go to Tanzania for the summer months to work hands-on with making the project happen together with the community group. The intention is to engage in Tanzania for at least five years, to that there can be continuity and ecosystem development in the field and accumulated learning within Aalto University.</p>
</div>
<div>
	<div id="flowcontainer" class="thumbnails">
		
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImageGroupCollection -->



	</div>
	<br>
	
<script>
	$(function(){
		var $container = $('#flowcontainer');
		$container.isotope({
		itemSelector: '.oipimagecollection'
		});
	});
</script>
</div>
<div class="reading-pane-footer">
    <div class="meta">
        <!--
        using same <dl></dl> as in tiles
        -->
        <dl class="dl-horizontal date"><dt>on</dt><dd>1/1/0001 12:00:00 AM</dd></dl>
        <dl class="dl-horizontal author"><dt>by</dt><dd></dd></dl>
    </div>
    <div class="controls">
        <ul class="inline">
            <li>
                <form>
                    <i class="icon-bookmark"></i>
                    <input class="text" name="share_url" value="http://www.aaltoglobalimpact.org/www-public/oip-layout-landing.phtml?type=activity&id=409bf342-57d8-4e8e-9094-ffd5b30e3e67">
                </form>
            </li>
        </ul>
    </div>
</div>


<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.Activity -->


