
<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.Blog -->

	<h2>
<!-- start oip-atom-subtitle.txt -->
<a data-id="7d17fee0-482b-4e8e-8f8c-595ff9e1736c_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">Weconomy launched on 21.9 at Nordic Business Forum in Jyväskylä</a>
<!-- end oip-atom-subtitle.txt -->



		<br>
		<small>
<!-- start oip-atom-subtitle.txt -->
<span class="small-before-after"/>"</span>
<a data-id="7d17fee0-482b-4e8e-8f8c-595ff9e1736c_SubTitle"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit"></a>
<span class="small-before-after"/>"</span>
<!-- end oip-atom-subtitle.txt -->
</small>
	</h2>
</div>
<div class="multicolumnElement" style="padding-left:15px;padding-right:15px;">
    <p>
        <img src="../AaltoGlobalImpact.OIP/MediaContent/5c61bd89-e748-435b-bbfb-44f4b1b0f71c_320x240_crop.jpg" />
    </p>
	<p>
		<span lang="">
<p>Would you take a step towards a business that supports well-being? Discover Weconomy Start - and develop your business ideas with end users representing low-income people across the world. Discover the opportunities of a market of four billion poor people, called Base of the Pyramid. Discover<a href="http://demooip.aaltoglobalimpact.org/auth/grp/9798daca-afc4-4046-a99b-d0d88bb364e0/website/oip-group/www.weconomy.fi"><span lang="">www.weconomy.fi</span></a><span lang="">. Launched today - on 21.9 at Nordic Business Forum Jyväskylä.</span></p></span>
	</p>
</div>
<div>
	<div id="flowcontainer" class="thumbnails">
		
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImageGroupCollection -->



	</div>
	<br>
	
<script>
    $(function(){
      var $container = $('#flowcontainer');
      $container.isotope({
        itemSelector: '.oipimagecollection'
      });
    });
</script>
</div>
<div class="reading-pane-footer">
    <div class="meta">
        <!--
        using same <dl></dl> as in tiles
        -->
        <dl class="dl-horizontal date"><dt>on</dt><dd>11/2/2012 1:25:03 PM</dd></dl>
        <dl class="dl-horizontal author"><dt>by</dt><dd>Aalto Global Impact </dd></dl>
    </div>
    <div class="controls">
        <ul class="inline">
            <li>
                <form>
                    <i class="icon-bookmark"></i>
                    <input class="text" name="share_url" value="http://www.aaltoglobalimpact.org/www-public/oip-layout-landing.phtml?type=news&id=7d17fee0-482b-4e8e-8f8c-595ff9e1736c">
                </form>
            </li>
        </ul>
    </div>
</div>


<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.Blog -->


