
<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.Blog -->

	<h2>
<!-- start oip-atom-subtitle.txt -->
<a data-id="a4789894-c044-4c0b-bda1-2f3d46c7641e_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">South Africa: World Design Capital 2012-2014</a>
<!-- end oip-atom-subtitle.txt -->



		<br>
		<small>
<!-- start oip-atom-subtitle.txt -->
<span class="small-before-after"/>"</span>
<a data-id="a4789894-c044-4c0b-bda1-2f3d46c7641e_SubTitle"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">Helsinki meets Cape Town</a>
<span class="small-before-after"/>"</span>
<!-- end oip-atom-subtitle.txt -->
</small>
	</h2>
</div>
<div class="multicolumnElement" style="padding-left:15px;padding-right:15px;">
    <p>
        <img src="../AaltoGlobalImpact.OIP/MediaContent/ece17733-4a6c-41e4-9850-94e076751151_320x240_crop.jpg" />
    </p>
	<p>
		<p>The succeeding World Design Capital years of Helsinki in 2012 and Cape Town in 2014 provide a unique opportunity for furthering partnerships between Finland and South Africa.&nbsp;This project aims at creating space for new longer-term collaboration and business opportunities between the two countries.</p>

<p>The Embassy of Finland in Pretoria plans to organize an event “Helsinki meets Cape Town” in November 2012. This high-profile event will be organized together with the cities of Helsinki and Cape Town, Finpro, Finnish companies, the Cape Peninsula University of Technology and Aalto University. Other partners are also being sought.</p>

<p>The program of the event will focus on various aspects of design, business and science. Socially, environmentally and economically important issues will be addressed and solutions sought/co-created during workshops which will take place in the townships of Cape Town.&nbsp;People working on design, shelter, water, sanitation and broad sustainable livelihoods issues are invited to join the planning of the event and the identification process of our longer-term collaborative projects.</p>

<p>In addition, the event aims at providing a platform connecting and enabling Finnish and South African companies to develop new businesses between the two countries. Finnish start-ups connected to Aalto University as well as larger companies already present or seeking new market opportunities in South Africa are targeted for this part of the event.</p>

<p>For more information, contact Anne Badan (anne.badan(at)aalto.fi)</p>

<p>See the video "cape Town - World Design Capital 2014"</p>
<p><a href="http://www.youtube.com/watch?v=XrcFSbYSEko">http://www.youtube.com/watch?v=XrcFSbYSEko</a></p>
	</p>
</div>
<div>
	<div id="flowcontainer" class="thumbnails">
		
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImageGroupCollection -->



	</div>
	<br>
	<iframe width="560" height="315" src="http://www.youtube.com/embed/XrcFSbYSEko" frameborder="0" allowfullscreen></iframe>
<script>
    $(function(){
      var $container = $('#flowcontainer');
      $container.isotope({
        itemSelector: '.oipimagecollection'
      });
    });
</script>
</div>
<div class="reading-pane-footer">
    <div class="meta">
        <!--
        using same <dl></dl> as in tiles
        -->
        <dl class="dl-horizontal date"><dt>on</dt><dd>3/31/2012 12:00:00 AM</dd></dl>
        <dl class="dl-horizontal author"><dt>by</dt><dd>Aalto Global Impact</dd></dl>
    </div>
    <div class="controls">
        <ul class="inline">
            <li>
                <form>
                    <i class="icon-bookmark"></i>
                    <input class="text" name="share_url" value="http://www.aaltoglobalimpact.org/www-public/oip-layout-landing.phtml?type=news&id=a4789894-c044-4c0b-bda1-2f3d46c7641e">
                </form>
            </li>
        </ul>
    </div>
</div>


<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.Blog -->


