
<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.Blog -->

	<h2>
<!-- start oip-atom-subtitle.txt -->
<a data-id="187ff763-f5d6-4a45-928f-3fb1ced37639_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">Peru: Innovation and Design for Furniture SMEs</a>
<!-- end oip-atom-subtitle.txt -->



		<br>
		<small>
<!-- start oip-atom-subtitle.txt -->
<span class="small-before-after"/>"</span>
<a data-id="187ff763-f5d6-4a45-928f-3fb1ced37639_SubTitle"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit"></a>
<span class="small-before-after"/>"</span>
<!-- end oip-atom-subtitle.txt -->
</small>
	</h2>
</div>
<div class="multicolumnElement" style="padding-left:15px;padding-right:15px;">
    <p>
        <img src="../AaltoGlobalImpact.OIP/MediaContent/764d4300-0b7a-4780-9bfe-fe56185670ab_320x240_crop.jpg" />
    </p>
	<p>
		<span lang="">
<p>The IDBM - CITEMadera project in Peru is a BoP (Base of the Pyramid) - themed project, which focuses on the creation of a business model and tools for CITEMadera to be used to improve innovation and design in furniture SMEs in Peru. </p>
<p>&nbsp;</p>
<p>The problem faced by the Aalto International Design Business Management (IDBM) team is that local furniture SMEs in Peru focus too heavily on replication or production of designs from a third party. An IDBM Team has been focusing on the project throughout the academic year: Eero Hintsanen from the School of Art and Design, Pekka Sihvola and Tiina Witikkala from the Schools of Science and Technology, Oscar Subirats (Spain) from HANKEN School of Economics, and Sun Huangying (China) double degree between IDBM Master Program in Aalto University School of Economics and Tongji University; all of them coached by Rodrigo Cervantes, IDBM Program Project Manager.</p>
<p>The project was divided into two distinctive phases. From September until December 2011, the team focused on furniture industry research for best practices, theoretical background and quantitative data collection of local SMEs in collaboration with a local team provided by the CITEMadera Peru. For the second phase, from January to May 2012, the team developed the business modeling tools, field-tested the tools and analyzed the findings to build a final proposal on the business modeling tools for CITEMadera.</p>
<p>&nbsp;</p>
<p>During a two-week field research trip to Lima in Peru, the team visited several local SMEs, wood workshops, sawmills and stores and intrviewed local design academics, industry experts and company owners. The team also ran a pilot seminar with three selected furniture SMEs to better test the tools with the target user, and analyzed the results and comments from the companies.</p>
<p>&nbsp;</p>
<p>The preliminary results revealed a resistance against design and innovation from owners of the SMEs, and also surprisingly from the Peruvian industrial designers themselves. The latter also lacked the technical know-how to propose viable designs that would meet the production opportunities of the local SMEs. The IDBM team was able to raise awareness and transmit to the owners of the selected SMEs the benefits of design thinking and business modeling tools. As a result, in collaboration with local young designers, the SME owners were able to produce an original prototype of a piece of furniture, which represents their company and meets their production capabilities.</p></span>
	</p>
</div>
<div>
	<div id="flowcontainer" class="thumbnails">
		
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImageGroupCollection -->



	</div>
	<br>
	
<script>
    $(function(){
      var $container = $('#flowcontainer');
      $container.isotope({
        itemSelector: '.oipimagecollection'
      });
    });
</script>
</div>
<div class="reading-pane-footer">
    <div class="meta">
        <!--
        using same <dl></dl> as in tiles
        -->
        <dl class="dl-horizontal date"><dt>on</dt><dd>2/28/2012 1:12:26 PM</dd></dl>
        <dl class="dl-horizontal author"><dt>by</dt><dd>Aalto Global Impact</dd></dl>
    </div>
    <div class="controls">
        <ul class="inline">
            <li>
                <form>
                    <i class="icon-bookmark"></i>
                    <input class="text" name="share_url" value="http://www.aaltoglobalimpact.org/www-public/oip-layout-landing.phtml?type=news&id=187ff763-f5d6-4a45-928f-3fb1ced37639">
                </form>
            </li>
        </ul>
    </div>
</div>


<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.Blog -->


