
<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.Blog -->

	<h2>
<!-- start oip-atom-subtitle.txt -->
<a data-id="c015b855-49f2-4300-9213-59d1468db579_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">Sujil Kodathoor</a>
<!-- end oip-atom-subtitle.txt -->



		<br>
		<small>
<!-- start oip-atom-subtitle.txt -->
<span class="small-before-after"/>"</span>
<a data-id="c015b855-49f2-4300-9213-59d1468db579_SubTitle"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit"></a>
<span class="small-before-after"/>"</span>
<!-- end oip-atom-subtitle.txt -->
</small>
	</h2>
</div>
<div class="multicolumnElement" style="padding-left:15px;padding-right:15px;">
    <p>
        <img src="../AaltoGlobalImpact.OIP/MediaContent/8664aded-9fe7-417e-b162-301a6285fe15_320x240_crop.jpg" />
    </p>
	<p>
		Sujil is a M.A. Student at Aalto Univeristy, studying Creative Sustainability. His added experience in the design industry includes product design, web services and design for social change.<br><br>His work in the United States, the Middle East and India provides him access to a global design network. He brings in knowledge of multi-disciplinary collaborative design for social impact and sustainability that contributes to social development. His work contributes to planning and organizing participatory process and implementing procedural changes in development projects focusing on measurable outcome. With his focus on design for sustainability and his skills and expertise of multidisciplinary design, he will focus on curating collaborative thinking, sketching fresh perspectives and molding actions for sustainable solutions.<br>
	</p>
</div>
<div>
	<div id="flowcontainer" class="thumbnails">
		
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImageGroupCollection -->



	</div>
	<br>
	
<script>
    $(function(){
      var $container = $('#flowcontainer');
      $container.isotope({
        itemSelector: '.oipimagecollection'
      });
    });
</script>
</div>
<div class="reading-pane-footer">
    <div class="meta">
        <!--
        using same <dl></dl> as in tiles
        -->
        <dl class="dl-horizontal date"><dt>on</dt><dd>3/19/2013 11:15:16 AM</dd></dl>
        <dl class="dl-horizontal author"><dt>by</dt><dd>Aalto Global Impact</dd></dl>
    </div>
    <div class="controls">
        <ul class="inline">
            <li>
                <form>
                    <i class="icon-bookmark"></i>
                    <input class="text" name="share_url" value="http://www.aaltoglobalimpact.org/www-public/oip-layout-landing.phtml?type=news&id=c015b855-49f2-4300-9213-59d1468db579">
                </form>
            </li>
        </ul>
    </div>
</div>


<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.Blog -->


