
<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.Activity -->

<h2><a data-id="e9ead5e9-9e6e-48cf-9ffb-34f65d16ca9d_ActivityName" title="Edit Activity Name" class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">Mozambique: Business Models for Local Producers</a>

</h2>

<!-- THEBALL-CONTEXT-OBJECT-BEGIN:Introduction -->

<!-- oip-module-introduction.txt -->
<h3>

<!-- start oip-atom-subtitle.txt -->
<a data-id="efc9a33e-7d98-4766-8bb7-e115c0eb2f87_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit"></a>
<!-- end oip-atom-subtitle.txt -->



</h3>
<p>
<a data-id="efc9a33e-7d98-4766-8bb7-e115c0eb2f87_Body"  class="noteditable open-IncontextEditDialog_Text_Long in-context-edit"></a>

</p>
<!-- end oip-module-introduction.txt -->


<!-- THEBALL-CONTEXT-END:Introduction -->

</div>
<div class="multicolumnElement" style="padding-left:15px;padding-right:15px;">
    <p>
        <img src="../AaltoGlobalImpact.OIP/MediaContent/57251982-d6cb-453c-9c49-7a7408e73031_320x240_crop.jpg" />
    </p>
    <p>A cross-disciplinary student group form the Creative Sustainability program completed a project in cooperation with the Ministry of Science and Technology in the Lionde Millennium Village (MV) in Gaza Province, Mozambique. 
The initial task was to develop local farmers’ and food processors’ businesses using a Base of the Pyramid (BoP) approach. Lionde has been part of the MV program since 2009, and the business development project was intended to partially contribute to Lionde becoming a self-sustaining community by 2014, i.e by the end of the 5-year MV program. In the project kick-off the students' group members were offered an opportunity to travel to Mozambique to conduct on-site research.
Prior to the trip, the students worked over skype meetings with the local contact. The scope of the project was narrowed down in order to develop a business model for the local producers. However, during the field research, the students concluded that the initial task of delivering a business model would not address the real problems the local producers struggle with, and could not currently be implemented at all, and therefore decided to expand the scope of the project to more fundamental issues in addition to the business model.
The students' decision to challenge the initial task was welcomed with enthusiasm by the parties involved, and the group felt they were contributing concretely to the current situation. The group felt fortunate to have had the opportunity to go to Mozambique to conduct the research and see for themselves the concrete impact of their work. In addition, they lived an exceptional experience, never to forget, since they stayed in the village living with local families, building a connection to real life.
The team is currently finalising their report but they already shared with us their preliminary conclusion: "The depth of the study reached a level that could not have been reached staying in Finland only, increasing the value of the output tremendously. The project continues with further research in Finland, based on the findings on-site, and the results are to be delivered in the end of the spring semester. Moreover, as lot of work, on a larger scale, is still to be done, and the client wishes the cooperation to continue at some level after the project, opportunities for collaboration on new projects exist for students and researchers enthusiastic about developing solutions in BoP-markets."
The team: Patrick Lees, Antti Hellgren, Jonathan Ko, Gospel Oparaocha, Nicholàs B. Torretta</p>
</div>
<div>
	<div id="flowcontainer" class="thumbnails">
		
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImageGroupCollection -->



	</div>
	<br>
	
<script>
	$(function(){
		var $container = $('#flowcontainer');
		$container.isotope({
		itemSelector: '.oipimagecollection'
		});
	});
</script>
</div>
<div class="reading-pane-footer">
    <div class="meta">
        <!--
        using same <dl></dl> as in tiles
        -->
        <dl class="dl-horizontal date"><dt>on</dt><dd>1/1/0001 12:00:00 AM</dd></dl>
        <dl class="dl-horizontal author"><dt>by</dt><dd></dd></dl>
    </div>
    <div class="controls">
        <ul class="inline">
            <li>
                <form>
                    <i class="icon-bookmark"></i>
                    <input class="text" name="share_url" value="http://www.aaltoglobalimpact.org/www-public/oip-layout-landing.phtml?type=activity&id=e9ead5e9-9e6e-48cf-9ffb-34f65d16ca9d">
                </form>
            </li>
        </ul>
    </div>
</div>


<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.Activity -->


