
<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.Blog -->

	<h2>
<!-- start oip-atom-subtitle.txt -->
<a data-id="347cce25-876f-4e2a-90b8-d8835b15762f_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">Teija Lehtonen</a>
<!-- end oip-atom-subtitle.txt -->



		<br>
		<small>
<!-- start oip-atom-subtitle.txt -->
<span class="small-before-after"/>"</span>
<a data-id="347cce25-876f-4e2a-90b8-d8835b15762f_SubTitle"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit"></a>
<span class="small-before-after"/>"</span>
<!-- end oip-atom-subtitle.txt -->
</small>
	</h2>
</div>
<div class="multicolumnElement" style="padding-left:15px;padding-right:15px;">
    <p>
        <img src="../AaltoGlobalImpact.OIP/MediaContent/f3b94be6-bb62-4abf-9103-37d00b5b3de2_320x240_crop.jpg" />
    </p>
	<p>
		Teija is Aalto Global Impact's Director. Her passion is co-creation and building inclusive innovation ecosystems together with poor people and communities. She has extensive international experience in business development, leading multicultural teams with different technical backgrounds, productive capacity building and participatory methodology.<br><br>Teija graduated from the School of Economics and has worked since then in Denmark, Ivory Coast, Sierra Leone, Abkhazia, India, Sri Lanka, Afghanistan, Nepal, Bangladesh and Pakistan in addition to her home country Finland. Her vision for Aalto Global Impact is to find new sustainable ways to create wealth and reduce poverty.<br>
	</p>
</div>
<div>
	<div id="flowcontainer" class="thumbnails">
		
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImageGroupCollection -->



	</div>
	<br>
	
<script>
    $(function(){
      var $container = $('#flowcontainer');
      $container.isotope({
        itemSelector: '.oipimagecollection'
      });
    });
</script>
</div>
<div class="reading-pane-footer">
    <div class="meta">
        <!--
        using same <dl></dl> as in tiles
        -->
        <dl class="dl-horizontal date"><dt>on</dt><dd>3/19/2013 11:17:42 AM</dd></dl>
        <dl class="dl-horizontal author"><dt>by</dt><dd>Aalto Global Impact</dd></dl>
    </div>
    <div class="controls">
        <ul class="inline">
            <li>
                <form>
                    <i class="icon-bookmark"></i>
                    <input class="text" name="share_url" value="http://www.aaltoglobalimpact.org/www-public/oip-layout-landing.phtml?type=news&id=347cce25-876f-4e2a-90b8-d8835b15762f">
                </form>
            </li>
        </ul>
    </div>
</div>


<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.Blog -->


