
<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.Blog -->

	<h2>
<!-- start oip-atom-subtitle.txt -->
<a data-id="5b69e13b-110f-426b-8b20-1cdc068f546f_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">GLOCAL: mNutrition for Infant Health – Global Mobile Platform Tested Locally in Rural India</a>
<!-- end oip-atom-subtitle.txt -->



		<br>
		<small>
<!-- start oip-atom-subtitle.txt -->
<span class="small-before-after"/>"</span>
<a data-id="5b69e13b-110f-426b-8b20-1cdc068f546f_SubTitle"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit"></a>
<span class="small-before-after"/>"</span>
<!-- end oip-atom-subtitle.txt -->
</small>
	</h2>
</div>
<div class="multicolumnElement" style="padding-left:15px;padding-right:15px;">
    <p>
        <img src="../AaltoGlobalImpact.OIP/MediaContent/e3949fb6-8d74-4261-b982-53a14963d5af_320x240_crop.jpg" />
    </p>
	<p>
		<span lang=""> 
<p>High infant mortality and health risks in India are linked to inappropriate feeding practices especially during the first two years of a child’s life. To address persistent challenges in feeding practices, Professor Marja Mutanen and her team from the University of Helsinki started an innovative Tekes-funded mHealth project – GloCal – in 2011. GloCal brings together nutritionists, anthropologists, e-learning experts, private Finnish companies, and local NGOs in India. Through the collaboration with Aalto Global Impact, MA Creative Sustainability student Sujil Kodathoor is contributing as a designer facilitator for GloCal. </p>
<p>&nbsp;</p>
<p>The GloCal pilot aims to bring vital nutritional education and health and dietary advice in the form of a mobile phone application to the mothers and healthcare workers in rural and semi-rural areas in India. Two mobile phone applications are currently being developed: one for the mothers of young infants (mMom) and the other one for healthcare personnel (mCare). Both of these applications disseminate appropriate nutrition information in new, innovative ways such as phone animations that includes an application to measure the impact of such knowledge sharing.</p>
<p>&nbsp;</p>
<p>The GloCal pilot is a first step within a longer-term objective to build a mAdvisory ecosystem to improve the health of both women and children globally by scaling up the successful Finnish social innovation, Neuvola, through the use of mobile phone technology. To provide real solutions to real people, the intended users of the products were extensively involved in the development process, with strong participation of public and private sectors, customers and beneficiaries. The project is based on nutritional and anthropological research, local dialogue and product design and development. The resulting application is being developed for field-testing by the end of the year.</p></span>
	</p>
</div>
<div>
	<div id="flowcontainer" class="thumbnails">
		
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImageGroupCollection -->



	</div>
	<br>
	
<script>
    $(function(){
      var $container = $('#flowcontainer');
      $container.isotope({
        itemSelector: '.oipimagecollection'
      });
    });
</script>
</div>
<div class="reading-pane-footer">
    <div class="meta">
        <!--
        using same <dl></dl> as in tiles
        -->
        <dl class="dl-horizontal date"><dt>on</dt><dd>11/2/2012 1:01:19 PM</dd></dl>
        <dl class="dl-horizontal author"><dt>by</dt><dd>Aalto Global Impact</dd></dl>
    </div>
    <div class="controls">
        <ul class="inline">
            <li>
                <form>
                    <i class="icon-bookmark"></i>
                    <input class="text" name="share_url" value="http://www.aaltoglobalimpact.org/www-public/oip-layout-landing.phtml?type=news&id=5b69e13b-110f-426b-8b20-1cdc068f546f">
                </form>
            </li>
        </ul>
    </div>
</div>


<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.Blog -->


