
<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.Activity -->

<h2><a data-id="35f3384c-0ff8-4333-9cd0-1b2405ac8a12_ActivityName" title="Edit Activity Name" class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">AGI TImeline</a>

</h2>

<!-- THEBALL-CONTEXT-OBJECT-BEGIN:Introduction -->

<!-- oip-module-introduction.txt -->
<h3>

<!-- start oip-atom-subtitle.txt -->
<a data-id="b5305651-be7f-402d-a2cb-1df610239dd9_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit"></a>
<!-- end oip-atom-subtitle.txt -->



</h3>
<p>
<a data-id="b5305651-be7f-402d-a2cb-1df610239dd9_Body"  class="noteditable open-IncontextEditDialog_Text_Long in-context-edit"></a>

</p>
<!-- end oip-module-introduction.txt -->


<!-- THEBALL-CONTEXT-END:Introduction -->

</div>
<div class="multicolumnElement" style="padding-left:15px;padding-right:15px;">
    <p>
        <img src="../AaltoGlobalImpact.OIP/MediaContent/5cb894b3-5ff7-4b12-810b-36ea3e291cfe_320x240_crop.jpg" />
    </p>
    <p><br></p>
</div>
<div>
	<div id="flowcontainer" class="thumbnails">
		
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ImageGroupCollection -->



	</div>
	<br>
	<iframe src='http://embed.verite.co/timeline/?source=0Auez1AQaMlCcdFhYNGtYUzdiMnJFQ0phYUhlUHkyY2c&font=Bevan-PotanoSans&maptype=watercolor&lang=en&height=570' width='99%' height='570' frameborder="0" allowfullscreen></iframe>

<script>
	$(function(){
		var $container = $('#flowcontainer');
		$container.isotope({
		itemSelector: '.oipimagecollection'
		});
	});
</script>
</div>
<div class="reading-pane-footer">
    <div class="meta">
        <!--
        using same <dl></dl> as in tiles
        -->
        <dl class="dl-horizontal date"><dt>on</dt><dd>2/19/2013 12:00:00 AM</dd></dl>
        <dl class="dl-horizontal author"><dt>by</dt><dd>Sujil Kodathoor</dd></dl>
    </div>
    <div class="controls">
        <ul class="inline">
            <li>
                <form>
                    <i class="icon-bookmark"></i>
                    <input class="text" name="share_url" value="http://www.aaltoglobalimpact.org/www-public/oip-layout-landing.phtml?type=activity&id=35f3384c-0ff8-4333-9cd0-1b2405ac8a12">
                </form>
            </li>
        </ul>
    </div>
</div>


<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.Activity -->


