<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title></title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">

<!-- Le styles -->
	<link href="../oip-additions/oip-assets/oip-js/google-code-prettify/prettify.css" rel="stylesheet">
    <link href="../oip-additions/oip-assets/oip-css/oip-bootstrap.css" rel="stylesheet">
    <link href="../oip-additions/oip-assets/oip-css/bootstrap-responsive.css" rel="stylesheet">

    <!--  <link href="../bootstrap-default/assets/css/jdpicker.css" rel="stylesheet">-->
<!--Extra Styles from jQuery UI-->
<!--  <link href="../third-party/jquery-ui/css/demo.css" rel="stylesheet">
  <link href="../third-party/jquery-ui/css/custom-theme/jquery-ui-1.8.16.custom.css" rel="stylesheet"> -->
<!-- calendar -->
<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

<!-- Le fav and touch icons -->
	<link rel="shortcut icon" href="../oip-additions/oip-assets/oip-images/icons/favicon.ico">
	<link rel="apple-touch-icon-precomposed" sizes="144x144" href="../oip-additions/oip-assets/oip-images/icons/favicon-OIP-144x144.png">
	<link rel="apple-touch-icon-precomposed" sizes="114x114" href="../oip-additions/oip-assets/oip-images/icons/favicon-OIP-114x114.png">
	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="../oip-additions/oip-assets/oip-images/icons/favicon-OIP-72x72.png">
	<link rel="apple-touch-icon-precomposed" href="../oip-additions/oip-assets/oip-images/icons/favicon-OIP-57x57.png">
	<link href="http://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css" rel="stylesheet">
	<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
	<script src="http://code.jquery.com/jquery-migrate-1.1.1.min.js"></script>
	<script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"></script>

    <link href="../oip-additions/oip-assets/oip-css/jquery-ui-timepicker-addon.css" rel="stylesheet">
	<script src="../oip-additions/oip-assets/oip-js/jquery-ui-timepicker-addon.js"></script>

	<script src="../oip-additions/oip-assets/oip-js/jquery.form.js"></script>
	<script src="../oip-additions/oip-assets/oip-js/jquery.masonry.min.js"></script>
	<script type="text/javascript" src="../oip-additions/oip-assets/oip-js/nicEdit.js"></script>
</head>

<body data-spy="scroll" data-target=".subnav" data-offset="50">
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
                <a class="aalto-navbar" href="http://www.aalto.fi/en">Aalto.fi</a>
    <ul>
        <li class="dropdown aalto-navbar">
            <a href="" class="dropdown-toggle" data-toggle="dropdown"
                    style="
                    color: #716b63 !important;
                    ">
                <span style="">Schools</span>
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li class="taik"><a href="http://arts.aalto.fi/en/">School of Arts, Design and Architecture</a></li>
                <li class="hse"><a href="http://business.aalto.fi/en/">School of Business</a></li>
                <li class="chem"><a href="http://chem.aalto.fi/en/">School of Chemical Technology</a></li>
                <li class="elec"><a href="http://elec.aalto.fi/en/">School of Electrical Engineering</a></li>
                <li class="eng"><a href="http://eng.aalto.fi/en/">School of Engineering</a></li>
                <li class="sci"><a href="http://sci.aalto.fi/en/" style="border: none;">School of Science</a></li>
            </ul>
        </li>
    </ul>
</php>
        </div>
    </div>
</div>
<div class="subnavbar">
    <div class="subnavbar-inner">
        <div class="container">
            <ul class="mainnav aaltoLogoType">
                <li xmlns="http://www.w3.org/1999/html">
        <p>
            <span class="aalto-mark-old aalto-a-old">A</span>
            <span class="aalto-mark-old">!</span>
        </p>
        <p>
            <span class="aalto-university-old">Aalto University</span><br>
            <span class="aalto-gi-old"><a href="../www-public/oip-layout-landing.phtml">Aalto Global Impact</a></span>
        </p>
    </a>
</li></php>
            </ul>
            <ul class="mainnav">
                <li>
                    <a href="#" class="oipmenuselector" data-locateto="#TileSection"
						data-filtername=".News">
                        <i class="icon-bullhorn news"></i>
                        <span>News</span>
                    </a>
                </li>
                <li class="dropdown">
                    <a href="" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-comments-alt activity"></i>
                        <span>Activities</span>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li> <a href="#" class="oipmenuselector" data-locateto="#TileSection" data-filtername=".Projects"> <i class="icon-time"></i> Projects</a> </li>
                        <li> <a href="#" class="oipmenuselector" data-locateto="#TileSection" data-filtername=".Events"> <i class="icon-flag"></i> Events</a> </li>
                        <li> <a href="#" class="oipmenuselector" data-locateto="#TileSection" data-filtername=".Blogs"> <i class="icon-bullhorn"></i> Blogs</a> </li>
                    </ul>
                </li>
				<li>
                    <a href="#" class="oipmenuselector" data-locateto="#TileSection"
						data-filtername=".Maps">
						<i class="icon-map-marker map"></i>
						<span>Maps</span>
					</a>
				</li>
                <li>
                    <a href="#" class="oipmenuselector" data-locateto="#TileSection"
						data-filtername=".About">
                        <i class="icon-umbrella about"></i>
                        <span>About</span>
                    </a>
                </li>
                <li>
                    <a href="http://demooip.aaltoglobalimpact.org/about/oip-public/oip-layout-register.phtml">
                        <i class="icon-star" style="color:#a9a9a9"></i>
                        <span>(OIP Beta)</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

<div class="container">
	<section id="container-focus" class="container well" >

<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.BlogContainer -->

<div class="services news-header small">

<!-- THEBALL-CONTEXT-OBJECT-BEGIN:Header -->

<div class="hero-unit">
    <h1>
<!-- start oip-atom-subtitle.txt -->
<a data-id="a5ca9d7d-fe3c-49fa-a832-9872d7d07bb0_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit"></a>
<!-- end oip-atom-subtitle.txt -->


</h1>
    <h1><small>
<!-- start oip-atom-subtitle.txt -->
<span class="small-before-after"/>"</span>
<a data-id="a5ca9d7d-fe3c-49fa-a832-9872d7d07bb0_SubTitle"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">AGI News now done</a>
<span class="small-before-after"/>"</span>
<!-- end oip-atom-subtitle.txt -->
</small></h1>
</div>



<!-- THEBALL-CONTEXT-END:Header -->

</div>
<div class="row-fluid">
    <div class="span3">
        
<!-- THEBALL-CONTEXT-OBJECT-BEGIN:BlogIndexGroup -->

<h4>
<!-- start oip-atom-subtitle.txt -->
<a data-id="683bf6e6-4b3f-4b45-bba6-d2672b3bfc8d_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">What should this be?</a>
<!-- end oip-atom-subtitle.txt -->


</h4>
<p><a data-id="683bf6e6-4b3f-4b45-bba6-d2672b3bfc8d_Introduction"  class="noteditable open-IncontextEditDialog_Text_Long in-context-edit"><a href="http://www.aaltoglobalimpact.org" title="AGI" target="">AGI </a>news happening around our community<br></a>
</p>
<div class="accordion index" id="accordion-blog-index">
    <div class="accordion-group accordion-group-index">
        <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion-blog-index" href="#collapse-accordion-blog-index-One">
                news by location
            </a>
        </div>
        <div id="collapse-accordion-blog-index-One" class="accordion-body collapse">
            <div class="accordion-inner accordion-group-index">
                <ul class="unstyled">
                    
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:GroupedByLocation -->



               </ul>
            </div>
        </div>
    </div>
    <div class="accordion-group accordion-group-index">
        <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion-blog-index" href="#collapse-accordion-blog-index-Two">
                news by date
            </a>
        </div>
        <div id="collapse-accordion-blog-index-Two" class="accordion-body collapse">
            <div class="accordion-inner accordion-group-index">
                <ul class="unstyled">
                    
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:GroupedByDate -->



                </ul>
            </div>
        </div>
    </div>
    <div class="accordion-group accordion-group-index">
        <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion-blog-index" href="#collapse-accordion-blog-index-Three">
                news by author
            </a>
        </div>
        <div id="collapse-accordion-blog-index-Three" class="accordion-body collapse">
            <div class="accordion-inner accordion-group-index">
                <ul class="unstyled">
                    
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:GroupedByAuthor -->


<li><div></div>
<ul>
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ReferenceCollection -->


<li><a href="AaltoGlobalImpact.OIP.Blog_f7c6f5d5-d063-4423-809f-924129b96377_DefaultView.phtml"> Master's award in development studies 2013</a></li>

<!-- THEBALL-CONTEXT-END:* -->

<li><a href="AaltoGlobalImpact.OIP.Blog_7f50acdc-b2d0-4f7c-93c4-5613984785e4_DefaultView.phtml"> Tanzania and Ethiopia: Enhancing Education and Research in Networking and Communications Engineering (ENhANCE)</a></li>

<!-- THEBALL-CONTEXT-END:* -->

</ul>
</li>


<!-- THEBALL-CONTEXT-END:GroupedByAuthor -->

<li><div>Aalto Global Impact</div>
<ul>
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ReferenceCollection -->


<li><a href="AaltoGlobalImpact.OIP.Blog_f021987f-5d23-42eb-a45f-1ef51bfe7c74_DefaultView.phtml"> Aalto Global Impact at MOA, May 14 on runaway urbanization, transforming businesses and sharing insights for societal change makers</a></li>

<!-- THEBALL-CONTEXT-END:* -->

<li><a href="AaltoGlobalImpact.OIP.Blog_800f8c4d-36e3-47e2-929e-25d5e99a19db_DefaultView.phtml"> Aalto PRO: Managing Urban Futures</a></li>

<!-- THEBALL-CONTEXT-END:* -->

<li><a href="AaltoGlobalImpact.OIP.Blog_7782a178-45e6-4219-8ba2-fc03a8e30e9e_DefaultView.phtml"> Aalto Global Impact</a></li>

<!-- THEBALL-CONTEXT-END:* -->

<li><a href="AaltoGlobalImpact.OIP.Blog_6eb6fdd7-c191-4102-af37-88666c2aaa33_DefaultView.phtml"> Aalto Global Impact Open Doors @ Design Factory on March 20</a></li>

<!-- THEBALL-CONTEXT-END:* -->

<li><a href="AaltoGlobalImpact.OIP.Blog_4f926db3-f622-402e-882d-16ab58f085a7_DefaultView.phtml"> Weconomy Start Kickoff Video, 22 January 2013</a></li>

<!-- THEBALL-CONTEXT-END:* -->

<li><a href="AaltoGlobalImpact.OIP.Blog_055cdd8d-c6b2-4b63-958d-364b84801169_DefaultView.phtml"> Call for Applications for the DocLinks Summer School 2013 - now open!</a></li>

<!-- THEBALL-CONTEXT-END:* -->

<li><a href="AaltoGlobalImpact.OIP.Blog_f3e4bcc6-97ed-4a0e-aaab-9fe85ad07c30_DefaultView.phtml"> Projects</a></li>

<!-- THEBALL-CONTEXT-END:* -->

</ul>
</li>


<!-- THEBALL-CONTEXT-END:GroupedByAuthor -->

<li><div>Via Aalto Sustainable Business Club</div>
<ul>
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:ReferenceCollection -->


<li><a href="AaltoGlobalImpact.OIP.Blog_7c1b99d6-b17f-4a3c-8210-bb3aab2a24c7_DefaultView.phtml"> Join the career night organized by Sustainable Business Club</a></li>

<!-- THEBALL-CONTEXT-END:* -->

</ul>
</li>


<!-- THEBALL-CONTEXT-END:GroupedByAuthor -->


                </ul>
            </div>
        </div>
    </div>
    <div class="accordion-group accordion-group-index">
        <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion-blog-index" href="#collapse-accordion-blog-index-Four">
                news by category
            </a>
        </div>
        <div id="collapse-accordion-blog-index-Four" class="accordion-body collapse">
            <div class="accordion-inner accordion-group-index">
                <ul class="unstyled">
                    
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:GroupedByCategory -->



                </ul>
            </div>
        </div>
    </div>
    <div class="accordion-group accordion-group-index">
        <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion-blog-index" href="#collapse-accordion-blog-index-Five">
                news archive (all)
            </a>
        </div>
        <div id="collapse-accordion-blog-index-Five" class="accordion-body collapse">
            <div class="accordion-inner accordion-group-index">
                <ul class="unstyled">
                    
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:FullBlogArchive -->


<li><a href="AaltoGlobalImpact.OIP.Blog_f7c6f5d5-d063-4423-809f-924129b96377_DefaultView.phtml">Master's award in development studies 2013</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_7c1b99d6-b17f-4a3c-8210-bb3aab2a24c7_DefaultView.phtml">Join the career night organized by Sustainable Business Club</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_f021987f-5d23-42eb-a45f-1ef51bfe7c74_DefaultView.phtml">Aalto Global Impact at MOA, May 14 on runaway urbanization, transforming businesses and sharing insights for societal change makers</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_7f50acdc-b2d0-4f7c-93c4-5613984785e4_DefaultView.phtml">Tanzania and Ethiopia: Enhancing Education and Research in Networking and Communications Engineering (ENhANCE)</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_800f8c4d-36e3-47e2-929e-25d5e99a19db_DefaultView.phtml">Aalto PRO: Managing Urban Futures</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_7782a178-45e6-4219-8ba2-fc03a8e30e9e_DefaultView.phtml">Aalto Global Impact</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_6eb6fdd7-c191-4102-af37-88666c2aaa33_DefaultView.phtml">Aalto Global Impact Open Doors @ Design Factory on March 20</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_4f926db3-f622-402e-882d-16ab58f085a7_DefaultView.phtml">Weconomy Start Kickoff Video, 22 January 2013</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_055cdd8d-c6b2-4b63-958d-364b84801169_DefaultView.phtml">Call for Applications for the DocLinks Summer School 2013 - now open!</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_f3e4bcc6-97ed-4a0e-aaab-9fe85ad07c30_DefaultView.phtml">Projects</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_598a4b5e-1ed6-4192-b08c-21334157053f_DefaultView.phtml">Events</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_360afc6f-130e-4cfd-9f63-df18da915afb_DefaultView.phtml">Aalto Global Impact Team</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_347cce25-876f-4e2a-90b8-d8835b15762f_DefaultView.phtml">Teija Lehtonen</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_64937264-b94b-4746-95b2-27dce2545759_DefaultView.phtml">Anne Badan</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_5b7b4d6b-8cfc-4fdb-bd62-cda4f09d3d1a_DefaultView.phtml">Riina Subra</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_bcc9d0ed-b260-4ca9-b29d-e8bc30ea5b7f_DefaultView.phtml">Andrew Clutterbuck</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_b5037e1b-1725-4719-aaac-a25e8b6fe92a_DefaultView.phtml">Rahim Saatov</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_c015b855-49f2-4300-9213-59d1468db579_DefaultView.phtml">Sujil Kodathoor</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_5bbf7c5d-4133-4915-bf33-f0ebe3d75a98_DefaultView.phtml">Irena Bakić wins the Women and Technology Prize</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_0e7aa6f5-bf71-44fa-b4aa-72ddc7e9a563_DefaultView.phtml">Tiia Kuokka got through the AGI Challenge</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_4170a423-00f9-4d87-871c-1401d3284f25_DefaultView.phtml">Tommi Rimpiläinen sheds light on the entrepreneurial processes in BOP markets </a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_2dbbcf10-3c60-488e-aa30-26f0be05dbb4_DefaultView.phtml">Invitation: Weconomy Start Kickoff, 22 January 2013</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_ec0c8fa6-64c8-475d-993f-9b0a3692ffe3_DefaultView.phtml">Sustainable Communities: Managing Urban Futures – Workshop for Supporting Sustainability</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_f594bdad-292e-4fcc-bf50-1f139d7d7da7_DefaultView.phtml">Blog entry by Thomas Banafa on Helsinki Sanitation Hackathon</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_704301f1-761e-48a8-aafb-945b37537a57_DefaultView.phtml">Talkoot: Cross-community Design workshop, Cape Town, South Africa</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_99a1d4bb-09c3-47d1-9265-5d9e169dc873_DefaultView.phtml">ACCESS: Design Needs Your Voice! Exploring Opportunity Gaps, Cape Town, South Africa</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_c0baeac5-bfc0-4aae-9d3d-2c0da47ed983_DefaultView.phtml">World Design Capital 2014 , Cape Town, South Africa</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_33d3f178-9d33-4b89-8a6a-f68abe36ab4e_DefaultView.phtml">Laura Ansala from Aalto University wins first Master's Award in Development Studies</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_479a1b4e-48ca-447d-8144-9113f04d3cc2_DefaultView.phtml">Internship at UN-HABITAT Nairobi office in Kenya</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_64d73ed4-35d6-4887-b634-e2abc09942d3_DefaultView.phtml">Master's Award in Development Studies - 2012</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_32d0899d-105f-419a-868e-1fd3b85db8de_DefaultView.phtml">Aalto Global Impact - internship announcement</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_48df3178-928b-4ad4-938a-c9567d99b7b7_DefaultView.phtml">Aalto Global Impact newsletter December 2012</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_de514c87-4aad-424c-a1f5-4a01ae4c2f8c_DefaultView.phtml">Safe and Sustainable Sanitation Workshop</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_3457eac7-7677-402f-abb3-9735e8345ae8_DefaultView.phtml"></a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_566a6297-594d-4c9d-9fae-f730423fe986_DefaultView.phtml">Aalto student talk</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_5e425198-40f9-42e5-b643-08d98ef28a39_DefaultView.phtml">Aalto Global Impact - UNICEF project newsletter</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_7d17fee0-482b-4e8e-8f8c-595ff9e1736c_DefaultView.phtml">Weconomy launched on 21.9 at Nordic Business Forum in Jyväskylä</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_9a739f07-2d32-451e-9143-387b5f36a37c_DefaultView.phtml">Invitation to event: Companies and NGOs - from Greenwashing to Innovations?</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_7cc8d059-5698-45de-bf2e-461680b7d388_DefaultView.phtml">India and Sri Lanka: Rapid Development for Inclusive Innovation</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_5b69e13b-110f-426b-8b20-1cdc068f546f_DefaultView.phtml">GLOCAL: mNutrition for Infant Health – Global Mobile Platform Tested Locally in Rural India</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_33b68341-3c2b-44ee-9bd6-6c433580d089_DefaultView.phtml">LEARN/SHARE: Commercialization and Scaling up Inclusive Businesses in Emerging Markets</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_87493283-5cba-4715-bf2d-d5a2eb3f8753_DefaultView.phtml">ACCESS: Matchmaking and Co-creation for New Collaborative Projects</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_9ec49203-fd65-4fed-92c0-416a3f9b794e_DefaultView.phtml">Social Impact through Creative Design - seminar</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_b3214363-da13-41a1-a869-951ea0f01a94_DefaultView.phtml"></a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_a8faa7b4-9fd8-47a4-bbef-4691dd8ece49_DefaultView.phtml"></a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_57461372-d0b9-4085-b82b-62b85ca36b14_DefaultView.phtml">Uganda: Water, Sanitation and Hygiene</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_dcdd09da-b4c1-4b76-aebc-ff943a4d0c22_DefaultView.phtml">Tanzania: Community and market improvement projects</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_6877e764-0e2e-4b47-9ce6-24ff367800be_DefaultView.phtml">F212 - Share your thoughts on the future – learn from others – have your ideas published – find out about the results</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_045e9d00-74b7-4ccb-b503-936362862cc5_DefaultView.phtml">Aalto - World Bank partnership: Training Program on Innovation Policy for ICT</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_906187a2-0957-49d3-ba68-6613363c0578_DefaultView.phtml">Aalto LAB Mexico, design for sustainability in the Maya community</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_a1ec4095-9960-4dbf-b8b9-343dd7d46d18_DefaultView.phtml">Lecture by Lee Bryant: Networked Innovation – Entrepreneurship for a Better Future</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_a4789894-c044-4c0b-bda1-2f3d46c7641e_DefaultView.phtml">South Africa: World Design Capital 2012-2014</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_187ff763-f5d6-4a45-928f-3fb1ced37639_DefaultView.phtml">Peru: Innovation and Design for Furniture SMEs</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href="AaltoGlobalImpact.OIP.Blog_90ca34e7-f4ca-48db-a720-7ef5e4fc4255_DefaultView.phtml">Mozambique: Business Models for Local Producers</a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->

<li><a href=""></a></li>


<!-- THEBALL-CONTEXT-END:FullBlogArchive -->


                </ul>
            </div>
        </div>
    </div>
</div>
<p><a data-id="683bf6e6-4b3f-4b45-bba6-d2672b3bfc8d_Summary"  class="noteditable open-IncontextEditDialog_Text_Long in-context-edit"><br></a>
</p>


<!-- THEBALL-CONTEXT-END:BlogIndexGroup -->

    </div>
    <div class="span9">
        
<!-- THEBALL-CONTEXT-OBJECT-BEGIN:RecentBlogSummary -->

<div class="" style="margin-bottom: 40px">
    
<!-- THEBALL-CONTEXT-OBJECT-BEGIN:Introduction -->

<!-- oip-module-introduction.txt -->
<h3>

<!-- start oip-atom-subtitle.txt -->
<a data-id="1d27c22c-593f-423a-aa0b-68615b638bff_Title"  class="noteditable open-IncontextEditDialog_Text_Short in-context-edit">News</a>
<!-- end oip-atom-subtitle.txt -->



</h3>
<p>
<a data-id="1d27c22c-593f-423a-aa0b-68615b638bff_Body"  class="noteditable open-IncontextEditDialog_Text_Long in-context-edit"><b><br></b></a>

</p>
<!-- end oip-module-introduction.txt -->


<!-- THEBALL-CONTEXT-END:Introduction -->

</div>
<div id="blogsummarycontainer">
    
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:RecentBlogCollection -->


<div class="blog-summary-item">
    <img class="img-style" src="../../AaltoGlobalImpact.OIP/MediaContent/079da9c1-ea97-4184-bed3-6749a5dcf2e8_320x240_crop.jpg" width="220"/>
    <h3>
        
<!-- THEBALL-CONTEXT-OBJECT-BEGIN:ReferenceToInformation -->

<a href="AaltoGlobalImpact.OIP.Blog_f7c6f5d5-d063-4423-809f-924129b96377_DefaultView.phtml">Master's award in development studies 2013</a>


<!-- THEBALL-CONTEXT-END:ReferenceToInformation -->

        <br><small>Have you written a high quality master’s thesis on global development or development studies? Or do you know someone who has?</small>
    </h3>
    <p><a data-id="f7c6f5d5-d063-4423-809f-924129b96377_Excerpt" data-title="Edit Excerpt" class="noteditable open-IncontextEditDialog_Text_Long in-context-edit">The Finnish University Partnership for International Development – UniPID and the Finnish Society for Development Research are jointly seeking exceptional Master’s level theses from UniPID universitie</a>
</<p>
    <a class="read-more" data-toggle="modal" href="AaltoGlobalImpact.OIP.Blog_f7c6f5d5-d063-4423-809f-924129b96377_DefaultView.phtml">Read More...</a>
    <ol class="unstyled">
        
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:CategoryCollection -->


<li><span class="badge category">News</span></li>

<!-- THEBALL-CONTEXT-END:CategoryCollection -->


    </ol>
</div>


<!-- THEBALL-CONTEXT-END:RecentBlogCollection -->

<div class="blog-summary-item">
    <img class="img-style" src="../../AaltoGlobalImpact.OIP/MediaContent/07450bf4-29d2-4ba2-abc1-e1631aa7607a_320x240_crop.jpg" width="220"/>
    <h3>
        
<!-- THEBALL-CONTEXT-OBJECT-BEGIN:ReferenceToInformation -->

<a href="AaltoGlobalImpact.OIP.Blog_7c1b99d6-b17f-4a3c-8210-bb3aab2a24c7_DefaultView.phtml">Join the career night organized by Sustainable Business Club</a>


<!-- THEBALL-CONTEXT-END:ReferenceToInformation -->

        <br><small>Five speakers sheds light into career paths in the field of sustainability</small>
    </h3>
    <p><a data-id="7c1b99d6-b17f-4a3c-8210-bb3aab2a24c7_Excerpt" data-title="Edit Excerpt" class="noteditable open-IncontextEditDialog_Text_Long in-context-edit">Five speakers representing companies big and small, as well as academia, shed light on what kind of career paths you can expect - or should be prepared to pioneer yourself. </a>
</<p>
    <a class="read-more" data-toggle="modal" href="AaltoGlobalImpact.OIP.Blog_7c1b99d6-b17f-4a3c-8210-bb3aab2a24c7_DefaultView.phtml">Read More...</a>
    <ol class="unstyled">
        
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:CategoryCollection -->


<li><span class="badge category">News</span></li>

<!-- THEBALL-CONTEXT-END:CategoryCollection -->


    </ol>
</div>


<!-- THEBALL-CONTEXT-END:RecentBlogCollection -->

<div class="blog-summary-item">
    <img class="img-style" src="../../AaltoGlobalImpact.OIP/MediaContent/d763b624-99b1-470c-84ba-bfe5f84f416c_320x240_crop.jpg" width="220"/>
    <h3>
        
<!-- THEBALL-CONTEXT-OBJECT-BEGIN:ReferenceToInformation -->

<a href="AaltoGlobalImpact.OIP.Blog_f021987f-5d23-42eb-a45f-1ef51bfe7c74_DefaultView.phtml">Aalto Global Impact at MOA, May 14 on runaway urbanization, transforming businesses and sharing insights for societal change makers</a>


<!-- THEBALL-CONTEXT-END:ReferenceToInformation -->

        <br><small>Co-creating sustainable opportunities for all</small>
    </h3>
    <p><a data-id="f021987f-5d23-42eb-a45f-1ef51bfe7c74_Excerpt" data-title="Edit Excerpt" class="noteditable open-IncontextEditDialog_Text_Long in-context-edit">Aalto Global Impact brings together inspirational speakers from business, civil society and academia. Key topics tackle mitigating problems of runaway urbanization, transforming existing business mode</a>
</<p>
    <a class="read-more" data-toggle="modal" href="AaltoGlobalImpact.OIP.Blog_f021987f-5d23-42eb-a45f-1ef51bfe7c74_DefaultView.phtml">Read More...</a>
    <ol class="unstyled">
        
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:CategoryCollection -->


<li><span class="badge category">News</span></li>

<!-- THEBALL-CONTEXT-END:CategoryCollection -->


    </ol>
</div>


<!-- THEBALL-CONTEXT-END:RecentBlogCollection -->

<div class="blog-summary-item">
    <img class="img-style" src="../../AaltoGlobalImpact.OIP/MediaContent/fa5449a8-49bb-4e40-bb3f-8b2f0daa372b_320x240_crop.jpg" width="220"/>
    <h3>
        
<!-- THEBALL-CONTEXT-OBJECT-BEGIN:ReferenceToInformation -->

<a href="AaltoGlobalImpact.OIP.Blog_7f50acdc-b2d0-4f7c-93c4-5613984785e4_DefaultView.phtml">Tanzania and Ethiopia: Enhancing Education and Research in Networking and Communications Engineering (ENhANCE)</a>


<!-- THEBALL-CONTEXT-END:ReferenceToInformation -->

        <br><small></small>
    </h3>
    <p><a data-id="7f50acdc-b2d0-4f7c-93c4-5613984785e4_Excerpt" data-title="Edit Excerpt" class="noteditable open-IncontextEditDialog_Text_Long in-context-edit">Aalto University, Addis Ababa Institute of Technology and University of Dar es Salaam are planning a partnership to promote the effective use of information and communication technologies (ICTs) in Et</a>
</<p>
    <a class="read-more" data-toggle="modal" href="AaltoGlobalImpact.OIP.Blog_7f50acdc-b2d0-4f7c-93c4-5613984785e4_DefaultView.phtml">Read More...</a>
    <ol class="unstyled">
        
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:CategoryCollection -->


<li><span class="badge category">News</span></li>

<!-- THEBALL-CONTEXT-END:CategoryCollection -->


    </ol>
</div>


<!-- THEBALL-CONTEXT-END:RecentBlogCollection -->

<div class="blog-summary-item">
    <img class="img-style" src="../../AaltoGlobalImpact.OIP/MediaContent/f8b4f5a3-ff49-4d5d-a84a-4996ad636091_320x240_crop.jpg" width="220"/>
    <h3>
        
<!-- THEBALL-CONTEXT-OBJECT-BEGIN:ReferenceToInformation -->

<a href="AaltoGlobalImpact.OIP.Blog_800f8c4d-36e3-47e2-929e-25d5e99a19db_DefaultView.phtml">Aalto PRO: Managing Urban Futures</a>


<!-- THEBALL-CONTEXT-END:ReferenceToInformation -->

        <br><small>Sustainable Communities Workshop, 12 – 22 March 2013, Dar es Salaam, Tanzania</small>
    </h3>
    <p><a data-id="800f8c4d-36e3-47e2-929e-25d5e99a19db_Excerpt" data-title="Edit Excerpt" class="noteditable open-IncontextEditDialog_Text_Long in-context-edit">Aalto PRO, together with various cooperation partners, organized a two week Sustainable Communities workshop in Dar es Salaam, Tanzania, in March 2013. </a>
</<p>
    <a class="read-more" data-toggle="modal" href="AaltoGlobalImpact.OIP.Blog_800f8c4d-36e3-47e2-929e-25d5e99a19db_DefaultView.phtml">Read More...</a>
    <ol class="unstyled">
        
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:CategoryCollection -->


<li><span class="badge category">News</span></li>

<!-- THEBALL-CONTEXT-END:CategoryCollection -->


    </ol>
</div>


<!-- THEBALL-CONTEXT-END:RecentBlogCollection -->

<div class="blog-summary-item">
    <img class="img-style" src="../../AaltoGlobalImpact.OIP/MediaContent/d6d3fb64-8dcd-4ca9-8b15-8df585d24cbb_320x240_crop.jpg" width="220"/>
    <h3>
        
<!-- THEBALL-CONTEXT-OBJECT-BEGIN:ReferenceToInformation -->

<a href="AaltoGlobalImpact.OIP.Blog_7782a178-45e6-4219-8ba2-fc03a8e30e9e_DefaultView.phtml">Aalto Global Impact</a>


<!-- THEBALL-CONTEXT-END:ReferenceToInformation -->

        <br><small></small>
    </h3>
    <p><a data-id="7782a178-45e6-4219-8ba2-fc03a8e30e9e_Excerpt" data-title="Edit Excerpt" class="noteditable open-IncontextEditDialog_Text_Long in-context-edit">Aalto Global Impact supports Aalto University's mission to change the world for a better place. We work as a catalyst and actively orient, shape and analyze the societal impact of Aalto University and</a>
</<p>
    <a class="read-more" data-toggle="modal" href="AaltoGlobalImpact.OIP.Blog_7782a178-45e6-4219-8ba2-fc03a8e30e9e_DefaultView.phtml">Read More...</a>
    <ol class="unstyled">
        
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:CategoryCollection -->


<li><span class="badge category">About</span></li>

<!-- THEBALL-CONTEXT-END:CategoryCollection -->


    </ol>
</div>


<!-- THEBALL-CONTEXT-END:RecentBlogCollection -->

<div class="blog-summary-item">
    <img class="img-style" src="../../AaltoGlobalImpact.OIP/MediaContent/f4172153-9e91-4c21-9eaa-fc52fbe311b1_320x240_crop.jpg" width="220"/>
    <h3>
        
<!-- THEBALL-CONTEXT-OBJECT-BEGIN:ReferenceToInformation -->

<a href="AaltoGlobalImpact.OIP.Blog_6eb6fdd7-c191-4102-af37-88666c2aaa33_DefaultView.phtml">Aalto Global Impact Open Doors @ Design Factory on March 20</a>


<!-- THEBALL-CONTEXT-END:ReferenceToInformation -->

        <br><small></small>
    </h3>
    <p><a data-id="6eb6fdd7-c191-4102-af37-88666c2aaa33_Excerpt" data-title="Edit Excerpt" class="noteditable open-IncontextEditDialog_Text_Long in-context-edit">We would love to spend the International Day of Happiness with you in Aalto Global Impact Open Doors @ Design Factory on March 20, 15:00-18:00. </a>
</<p>
    <a class="read-more" data-toggle="modal" href="AaltoGlobalImpact.OIP.Blog_6eb6fdd7-c191-4102-af37-88666c2aaa33_DefaultView.phtml">Read More...</a>
    <ol class="unstyled">
        
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:CategoryCollection -->


<li><span class="badge category">News</span></li>

<!-- THEBALL-CONTEXT-END:CategoryCollection -->

<li><span class="badge category">Events</span></li>

<!-- THEBALL-CONTEXT-END:CategoryCollection -->


    </ol>
</div>


<!-- THEBALL-CONTEXT-END:RecentBlogCollection -->

<div class="blog-summary-item">
    <img class="img-style" src="../../AaltoGlobalImpact.OIP/MediaContent/748523b3-e6e2-4fa7-9b33-b44d2a754833_320x240_crop.jpg" width="220"/>
    <h3>
        
<!-- THEBALL-CONTEXT-OBJECT-BEGIN:ReferenceToInformation -->

<a href="AaltoGlobalImpact.OIP.Blog_4f926db3-f622-402e-882d-16ab58f085a7_DefaultView.phtml">Weconomy Start Kickoff Video, 22 January 2013</a>


<!-- THEBALL-CONTEXT-END:ReferenceToInformation -->

        <br><small></small>
    </h3>
    <p><a data-id="4f926db3-f622-402e-882d-16ab58f085a7_Excerpt" data-title="Edit Excerpt" class="noteditable open-IncontextEditDialog_Text_Long in-context-edit"></a>
</<p>
    <a class="read-more" data-toggle="modal" href="AaltoGlobalImpact.OIP.Blog_4f926db3-f622-402e-882d-16ab58f085a7_DefaultView.phtml">Read More...</a>
    <ol class="unstyled">
        
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:CategoryCollection -->


<li><span class="badge category">News</span></li>

<!-- THEBALL-CONTEXT-END:CategoryCollection -->


    </ol>
</div>


<!-- THEBALL-CONTEXT-END:RecentBlogCollection -->

<div class="blog-summary-item">
    <img class="img-style" src="../../AaltoGlobalImpact.OIP/MediaContent/6b1187b4-911d-4ead-b4d2-8d3224232b3e_320x240_crop.jpg" width="220"/>
    <h3>
        
<!-- THEBALL-CONTEXT-OBJECT-BEGIN:ReferenceToInformation -->

<a href="AaltoGlobalImpact.OIP.Blog_055cdd8d-c6b2-4b63-958d-364b84801169_DefaultView.phtml">Call for Applications for the DocLinks Summer School 2013 - now open!</a>


<!-- THEBALL-CONTEXT-END:ReferenceToInformation -->

        <br><small></small>
    </h3>
    <p><a data-id="055cdd8d-c6b2-4b63-958d-364b84801169_Excerpt" data-title="Edit Excerpt" class="noteditable open-IncontextEditDialog_Text_Long in-context-edit">UniPID, in cooperation with the University of Helsinki, will host the second DocLinks Summer School in Helsinki, Finland on July 2-5, 2013. The call for Applications for the DocLinks Summer School 201</a>
</<p>
    <a class="read-more" data-toggle="modal" href="AaltoGlobalImpact.OIP.Blog_055cdd8d-c6b2-4b63-958d-364b84801169_DefaultView.phtml">Read More...</a>
    <ol class="unstyled">
        
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:CategoryCollection -->


<li><span class="badge category">News</span></li>

<!-- THEBALL-CONTEXT-END:CategoryCollection -->


    </ol>
</div>


<!-- THEBALL-CONTEXT-END:RecentBlogCollection -->

<div class="blog-summary-item">
    <img class="img-style" src="../../AaltoGlobalImpact.OIP/MediaContent/6601dfbb-a870-4d01-afce-1799ca88ab08_320x240_crop.jpg" width="220"/>
    <h3>
        
<!-- THEBALL-CONTEXT-OBJECT-BEGIN:ReferenceToInformation -->

<a href="AaltoGlobalImpact.OIP.Blog_f3e4bcc6-97ed-4a0e-aaab-9fe85ad07c30_DefaultView.phtml">Projects</a>


<!-- THEBALL-CONTEXT-END:ReferenceToInformation -->

        <br><small></small>
    </h3>
    <p><a data-id="f3e4bcc6-97ed-4a0e-aaab-9fe85ad07c30_Excerpt" data-title="Edit Excerpt" class="noteditable open-IncontextEditDialog_Text_Long in-context-edit">In order to nurture longer-term collaborations between Aalto University's programs and international partners, Aalto Global Impact assists its community through:
    </a>
</<p>
    <a class="read-more" data-toggle="modal" href="AaltoGlobalImpact.OIP.Blog_f3e4bcc6-97ed-4a0e-aaab-9fe85ad07c30_DefaultView.phtml">Read More...</a>
    <ol class="unstyled">
        
<!-- THEBALL-CONTEXT-COLLECTION-BEGIN:CategoryCollection -->


<li><span class="badge category">About</span></li>

<!-- THEBALL-CONTEXT-END:CategoryCollection -->


    </ol>
</div>


<!-- THEBALL-CONTEXT-END:RecentBlogCollection -->


</div>
<script>
	var $container = $('#blogsummarycontainer');
	$container.imagesLoaded(function(){
	  $container.masonry({
		itemSelector : '.blog-summary-item',
		// columnWidth : 240
		columnWidth: function( containerWidth ) {
		    return containerWidth / 5;
		}
	  });
	});
</script>


<!-- THEBALL-CONTEXT-END:RecentBlogSummary -->

    </div>
</div>

<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.BlogContainer -->

	</section>
	<section class="container well">

<!-- THEBALL-CONTEXT-ROOT-BEGIN:AaltoGlobalImpact.OIP.ContactOipContainer -->

<div class="hero-unit contact-oip">
    
<!-- ========== Begin: www-public\..\oip-containers\../oip-modules/oip-module-contact-oip.txt ========== -->
<!-- oip-module-footer.txt -->
	<p>
	<a href="http://demooip.aaltoglobalimpact.org/about/oip-public/oip-layout-register.phtml" class="btn btn-primary btn-large">Visit us at the Open Innovation Platform</a>
	</p>
<!-- end oip-module-footer.txt -->

<!-- ========== End: www-public\..\oip-containers\../oip-modules/oip-module-contact-oip.txt ========== -->

</div>


<!-- THEBALL-CONTEXT-END:AaltoGlobalImpact.OIP.ContactOipContainer -->

    </section>
</div>
<footer class="footer">
    <div class="container"><div class="span12">
        <p class="pull-right"><a href="#">Back to top</a></p>
    </div>
        <div class="span4">
            <ul class="aalto-footer">
                <li >
                    <a href="http://www.aalto.fi/en">Aalto.fi</a>
                    <ul>
                        <li class="taik"><a href="http://arts.aalto.fi/en/">School of Arts, Design and Architecture</a></li>
                        <li class="hse"><a href="http://business.aalto.fi/en/">School of Business</a></li>
                        <li class="chem"><a href="http://chem.aalto.fi/en/">School of Chemical Technology</a></li>
                        <li class="elec"><a href="http://elec.aalto.fi/en/">School of Electrical Engineering</a></li>
                        <li class="eng"><a href="http://eng.aalto.fi/en/">School of Engineering</a></li>
                        <li class="sci"><a href="http://sci.aalto.fi/en/" style="border: none;">School of Science</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="span4">
            <p>Aalto Global Impact has been formed to bring together these existing parties working in societal issues and to help them develop their activities further</p>
        </div>
        <div class="span3">
            <p>The <a id="edittoggle">Open</a> Innovation Platform is offered to you by Aalto Global Impact, and Aalto University organisation</p>
            <p>All content licensed under the <a href="http://www.apache.org/licenses/LICENSE-2.0" target="_blank">Apache License v2.0</a>. Documentation licensed under <a href="http://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>.</p>
            <p>Icons from <a href="http://fortawesome.github.com/Font-Awesome/">Font Awesome</a>, licensed under <a href="http://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>.</p>
        </div>
    </div>
</footer>


<!-- ========== Begin: www-public\..\oip-containers\../oip-modals/oip-modal-collection.txt ========== -->
<!-- oip-modal-collection.txt -->

<!-- ========== Begin: www-public\..\oip-containers\..\oip-modals\oip-modal-text-short.txt ========== -->
<!-- oip-modal-header.txt -->
<div class="modal hide fade well in-context-edit" id="IncontextEditDialog_Text_Short">
	<div class="modal-header">
		<button class="close" data-dismiss="modal">close</button> 
	</div>
	<form method="post">
		<div class="modal-body">
			<input id="InContextEditFieldID" name="InContextEditFieldID" type="hidden" value="NotSet" />
			<input id="RootSourceAction" name="RootSourceAction" type="hidden" value="Save" />
			<input class="span4" type="text" name="Text_Short" id="Text_Short" value="" />
<div class="control-group controls">
	<div class="form-actions" style="padding:0;margin:0;border-top:0;background-color:transparent;">
		<button value="true" name="btnCancel" class="btn">Cancel</button>
		<button type="submit" class="btn btn-primary" name="RootSourceAction" id="RootSourceAction" value="">Save changes</button>
	</div>
</div>

		</div>
	</form>
</div>
<!-- end oip-modal-header.txt -->

<!-- ========== End: www-public\..\oip-containers\..\oip-modals\oip-modal-text-short.txt ========== -->


<!-- ========== Begin: www-public\..\oip-containers\..\oip-modals\oip-modal-text-long.txt ========== -->
<!-- oip-modal-text-long.txt -->
<div class="modal hide fade well" id="IncontextEditDialog_Text_Long">
	<div class="modal-header">
		<button class="close" data-dismiss="modal">close</button> 
	</div>
	<form method="post">
		<div class="modal-body">
			<input id="InContextEditFieldID" name="InContextEditFieldID" type="hidden" value="NotSet" />
			<input id="RootSourceAction" name="RootSourceAction" type="hidden" value="Save" />
			<textarea class="span5" rows="30" id="Text_Long" name="Text_Long"></textarea>

<div class="control-group controls">
	<div class="form-actions" style="padding:0;margin:0;border-top:0;background-color:transparent;">
		<button value="true" name="btnCancel" class="btn">Cancel</button>
		<button type="submit" class="btn btn-primary" name="RootSourceAction" id="RootSourceAction" value="">Save changes</button>
	</div>
</div>

		</div>
	</form>
	<script type="text/javascript">
		function addRichTextEditTextLong() {
			richArea = new nicEditor({fullPanel : true, iconsPath : '../oip-additions/oip-assets/oip-js/nicEditorIcons.gif' }).panelInstance('Text_Long');
		}
		// Moved to actual dialog initiation script as the content weren't appearing from previous data
		// bkLib.onDomLoaded(function() { addRichTextEditTextLong(); });
	</script>
</div>
<!-- end oip-modal-text-long.txt -->

<!-- ========== End: www-public\..\oip-containers\..\oip-modals\oip-modal-text-long.txt ========== -->

<div class="modal hide fade well in-context-edit" id="IDAction_ConfirmRemove">
	<div class="modal-header">
		<button class="close" data-dismiss="modal">close</button> 
	</div>
	<form method="post">
		<div class="modal-body">
			<input id="ObjectFieldID" name="ObjectFieldID" type="hidden" value="NotSet" />
			<input id="RootSourceAction" name="RootSourceAction" type="hidden" value="" />
			<p name="question" id="question">Not set</p>
<div class="control-group controls">
	<div class="form-actions" style="padding:0;margin:0;border-top:0;background-color: transparent">
		<button value="true" name="btnCancel"  class="btn">Cancel</button>
		<button type="submit" class="btn btn-primary btn-danger" name="bDelete" id="bDelete" value="Delete">Delete</button>
	</div>
</div>

		</div>
	</form>
</div>

<div class="modal hide fade well" id="IDRemoteUrlModal" style="overflow-y:none;overflow:none">
	<div class="modal-header">
		<button class="close" data-dismiss="modal">close</button> 
	</div>
	<div id="IDRemoteUrlModalBody" style="max-height:420px;overflow-y:auto">
		Loading content...
	</div>
</div>

<!-- end oip-modal-collection.txt -->
<!-- ========== End: www-public\..\oip-containers\../oip-modals/oip-modal-collection.txt ========== -->



<script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
<script src="../oip-additions/oip-assets/oip-js/google-code-prettify/prettify.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-transition.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-alert.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-modal.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-dropdown.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-scrollspy.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-tab.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-tooltip.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-popover.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-button.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-collapse.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-carousel.js"></script>
<script src="../oip-additions/oip-assets/oip-js/bootstrap-typeahead.js"></script>
<!-- calendar -->
<script src="../oip-additions/oip-assets/oip-js/third-party-calendar.js"></script>
<!-- OIP specific -->
<script src="../oip-additions/oip-assets/oip-js/in-context-editing.js"></script>
<script src="../oip-additions/oip-assets/oip-js/modal-id-actions.js"></script>
</body>
</html>
